export const EDITORIAL_FONTS_LINK = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,600;0,700;1,500&family=PT+Serif:ital,wght@0,400;0,700;1,400&family=PT+Mono&family=Caveat:wght@400;500;600&family=Manrope:wght@400;500;600&display=swap" rel="stylesheet">';

const BASE = `
.sheet.gazette,.sheet.protokol,.sheet.postcard{--ed-serif:'Cormorant Garamond',Georgia,serif;--ed-body:'PT Serif',Georgia,serif;--ed-sans:'Manrope',Arial,sans-serif;--ed-script:'Caveat',cursive;--ed-mono:'PT Mono',monospace;max-width:38rem;font-family:var(--ed-body);color:var(--ed-ink);background:var(--ed-paper);overflow:clip}
.ed-section{position:relative;padding:46px 30px;text-align:center;overflow-wrap:anywhere}
.ed-section figure{margin:0}.ed-section p{font-size:16px;line-height:1.8}.ed-section p+p{margin-top:18px}
.ed-heading{margin:0 0 24px;font:600 clamp(28px,6vw,38px)/1.1 var(--ed-serif);color:inherit}.ed-heading::after{display:none}
.ed-section h3{font:600 26px/1.2 var(--ed-serif);margin:0 0 14px}.ed-tag{margin-bottom:14px;letter-spacing:.16em;text-transform:uppercase;font:500 12px/1.6 var(--ed-sans)!important}
.ed-photo{position:relative;overflow:hidden}.ed-photo img{display:block;width:100%;height:100%;object-fit:cover;margin:0}
.ed-placeholder{min-height:180px;display:grid;place-items:center;border:1px dashed currentColor}
.ed-names{font:500 clamp(32px,8vw,48px)/1.05 var(--ed-serif);margin:0;max-width:100%;overflow-wrap:anywhere;letter-spacing:-.02em}.ed-names i{font-weight:400;color:var(--ed-accent)}
.ed-date{margin:18px 0;font:500 14px/1.5 var(--ed-sans);letter-spacing:.1em}
.ed-script{font:500 24px/1.25 var(--ed-script)!important}.ed-scroll{margin-top:22px;opacity:.75}
.ed-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.ed-gallery:has(figure:only-child){grid-template-columns:1fr}
.ed-gallery .ed-photo{aspect-ratio:3/4}.ed-gallery figcaption,.ed-lead-photo figcaption{font-size:13px;line-height:1.6;margin-top:12px}
.ed-venue-photo{height:300px;margin:24px 0}.ed-outfits{height:260px;margin-top:26px}.ed-palette{display:flex;flex-wrap:wrap;justify-content:center;gap:13px;margin:28px auto}.ed-palette>span{width:54px;height:54px;border:1px solid #00000012;border-radius:50%}
.ed-button,.ed-open{display:inline-flex;justify-content:center;align-items:center;gap:8px;min-height:48px;max-width:100%;padding:13px 24px;margin-top:24px;background:var(--ed-accent);color:var(--ed-button-text,#fff);border:1px solid var(--ed-accent);font:500 14px/1.5 var(--ed-sans);text-decoration:none;white-space:normal;overflow-wrap:anywhere;cursor:pointer}
.ed-button:hover,.ed-open:hover{filter:brightness(1.12)}.ed-button:focus-visible,.ed-open:focus-visible,.ed-music-toggle:focus-visible{outline:2px solid var(--ed-accent);outline-offset:5px}
.ed-calendar-paper{max-width:330px;margin:0 auto 22px}.ed-month{margin:0 0 20px!important;letter-spacing:.12em;text-transform:uppercase;font:500 14px/1.6 var(--ed-sans)!important}
.ed-calendar{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px}.ed-calendar>span{display:grid;place-items:center;position:relative;min-height:36px;font:400 17px/1 var(--ed-body)}.ed-calendar .ed-weekday{font-size:12px;opacity:.65;min-height:28px}
.ed-calendar .ed-selected{border:1px solid currentColor;border-radius:50%;font-weight:700;color:var(--ed-accent)}
.ed-program{list-style:none;margin:0;padding:0;text-align:left}.ed-program li{display:grid;grid-template-columns:74px minmax(0,1fr);gap:18px;padding:21px 0;border-top:1px solid var(--ed-line)}.ed-program li:first-child{border-top:0;padding-top:0}.ed-program h3{font-size:23px;margin-bottom:8px}.ed-program p{font-size:14px;line-height:1.65}.ed-program time{font:500 24px/1.2 var(--ed-serif);color:var(--ed-accent)}
.ed-countdown .vm-cd{gap:8px}.ed-countdown .vm-cd-cell{border-color:var(--ed-line);background:transparent;border-radius:0;padding:18px 4px}.ed-countdown .vm-cd-num{font-family:var(--ed-serif);font-size:40px}.ed-countdown .vm-cd-label{font-size:11px;font-family:var(--ed-sans);letter-spacing:.08em}
.ed-rsvp .vm-rsvp{max-width:440px;margin:24px auto 0;text-align:left}.ed-rsvp .vm-rsvp-submit{width:100%}
.ed-intro[hidden]{display:none!important}.ed-intro{position:fixed;inset:0;z-index:100;display:grid;place-items:center;overflow:auto;padding:30px 20px;background:var(--ed-paper);color:var(--ed-ink)}
.ed-intro-content{width:min(100%,380px);text-align:center}.ed-intro-content>h2{font:500 36px/1.05 var(--ed-serif);margin:0 0 18px}.ed-intro-content>h2::after{display:none}.ed-intro-content>p{font-size:16px;line-height:1.6}
.ed-intro-paper{position:relative;min-height:230px;margin:38px auto 6px;padding:26px 22px;border:1px solid var(--ed-line);box-shadow:0 18px 35px #00000012;background:var(--ed-paper);transform:rotate(-4deg);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px}
.ed-intro-paper>span{font:600 25px/1.15 var(--ed-serif)}.ed-intro-lines{display:block;width:100%;height:62px;background:repeating-linear-gradient(0deg,transparent 0 10px,var(--ed-line) 11px 12px,transparent 13px 16px);opacity:.7}
.ed-seal{font:500 30px/1.1 var(--ed-script);color:var(--ed-accent)}.ed-intro-settings{margin:0 0 24px;padding:12px;border:1px dashed currentColor;text-align:left}.ed-intro-art{display:block;width:160px;height:180px;object-fit:contain}
.ed-music-toggle{position:fixed;z-index:40;bottom:16px;right:16px;max-width:180px;min-height:44px;border:1px solid var(--ed-line);border-radius:30px;background:var(--ed-paper);color:var(--ed-ink);padding:10px 16px;font:500 12px/1.4 var(--ed-sans)}
@media(max-width:480px){.ed-section{padding:36px 22px}.ed-cover{padding-top:26px}.ed-section p{font-size:14px;line-height:1.75}.ed-heading{font-size:30px}.ed-gallery{gap:12px}.ed-venue-photo{height:240px}.ed-outfits{height:220px}.ed-palette{gap:9px}.ed-palette>span{width:46px;height:46px}.ed-program li{grid-template-columns:58px minmax(0,1fr);gap:14px}.ed-program h3{font-size:22px}.ed-program time{font-size:24px}.ed-program p{font-size:13px}.ed-countdown .vm-cd-num{font-size:32px}.ed-countdown .vm-cd-label{font-size:10px}.ed-intro-content>h2{font-size:32px}.ed-intro-paper{margin-top:30px;min-height:200px}}
@media(prefers-reduced-motion:reduce){.ed-button,.ed-open{transition:none}}
`;

const GAZETTE = `
.sheet.gazette{--ed-paper:#f4f2eb;--ed-ink:#292923;--ed-accent:#45453b;--ed-line:#9d9b8d;background-image:radial-gradient(#b9b39e12 .7px,transparent .7px);background-size:5px 5px}
.gazette .ed-section:not(.ed-cover){border-top:1px solid var(--ed-line);margin-inline:26px;padding-inline:0}.gazette .ed-cover{padding:26px}
.gazette .ed-masthead>p{border-block:4px double currentColor;padding:10px 0;font:700 clamp(22px,6.2vw,36px)/1.05 var(--ed-body);letter-spacing:.035em;text-transform:uppercase}
.gazette .ed-edition{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--ed-line);text-align:center}.gazette .ed-edition .ed-date,.gazette .ed-edition>p{font:400 12px/1.5 var(--ed-body);margin:0;padding:9px 4px}.gazette .ed-edition>p+p{border-left:1px solid var(--ed-line)}
.gazette .ed-cover-copy{padding:30px 0 24px}.gazette .ed-cover-copy .ed-script{font:400 italic 17px/1.5 var(--ed-body)!important;margin-bottom:12px}.gazette .ed-names{text-transform:uppercase;font-weight:600;font-size:38px;letter-spacing:-.035em}.gazette .ed-names i{font-size:.75em;text-transform:none;color:inherit}
.gazette .ed-cover-image{height:min(66svh,530px);min-height:330px}.gazette .ed-lead-photo figcaption{font-style:italic}.gazette .ed-editorial-note{margin:26px 0 0;text-align:left}.gazette .ed-editorial-note::first-letter{float:left;font:700 52px/.95 var(--ed-body);padding:5px 9px 0 0}
.gazette .ed-heading{font:700 27px/1.15 var(--ed-body);text-transform:uppercase;letter-spacing:.035em}.gazette .ed-note{text-align:left}.gazette .ed-note .ed-heading{text-align:center}.gazette .ed-calendar-paper{border:1px solid var(--ed-line);padding:20px}.gazette .ed-selected{border-radius:0}
.gazette .ed-countdown .vm-cd-cell{border-inline:0;border-top:3px double var(--ed-line);border-bottom:3px double var(--ed-line)}.gazette .ed-intro-paper{border-block:4px double var(--ed-ink)}.gazette .ed-intro-paper>span{text-transform:uppercase;font:700 25px/1.1 var(--ed-body)}
@media(max-width:480px){.gazette .ed-cover{padding:24px 22px}.gazette .ed-section:not(.ed-cover){margin-inline:22px}.gazette .ed-cover-copy{padding-top:25px}.gazette .ed-cover-image{height:min(65svh,500px);min-height:300px}.gazette .ed-heading{font-size:24px}}
`;

const PROTOKOL = `
.sheet.protokol{--ed-paper:#eeece7;--ed-ink:#292929;--ed-accent:#7c3438;--ed-line:#c5c3bb;--ed-body:var(--ed-mono);max-width:38rem;background-image:linear-gradient(90deg,#d4d0c733,transparent 12%,transparent 88%,#d4d0c733)}
.protokol .ed-section{text-align:left}.protokol .ed-heading{font:700 23px/1.45 var(--ed-mono);letter-spacing:.035em;text-align:left;text-transform:uppercase;border-block:1px solid var(--ed-line);padding:15px 0;margin-bottom:26px}.protokol .ed-section p{font:400 14px/1.9 var(--ed-mono)}
.protokol .ed-document-title{margin:14px 0 10px;text-align:center;font:700 clamp(30px,8.7vw,44px)/1.1 var(--ed-mono);letter-spacing:.15em;text-transform:uppercase}.protokol .ed-document-title::after{display:none}.protokol .ed-document-subtitle{text-align:center!important;font-size:13px!important;font-weight:700!important;margin-bottom:30px}
.protokol .ed-statement{margin-bottom:18px;font-size:13px!important}.protokol .ed-person+.ed-person{margin-top:44px}.protokol .ed-form-lines{display:grid;gap:15px}.protokol .ed-letter-boxes{min-height:45px;border:1px solid var(--ed-line);background-image:repeating-linear-gradient(90deg,transparent 0 32px,var(--ed-line) 32px 33px);display:grid;place-items:center;padding:3px 10px}.protokol .ed-written{font:500 29px/1.25 var(--ed-script);overflow-wrap:anywhere;max-width:100%;text-align:center}.protokol .ed-field-hint{display:block;text-align:center;font:400 9px/1.5 var(--ed-mono);letter-spacing:.16em;margin-top:5px;color:#7d7a73}
.protokol .ed-evidence{position:relative;width:82%;max-width:290px;margin:32px auto 0;padding:12px 12px 15px;background:#fffdfa;box-shadow:0 12px 24px #00000012;transform:rotate(-2deg)}.protokol .ed-person:nth-of-type(2) .ed-evidence{transform:rotate(3deg)}.protokol .ed-evidence::before{content:'';position:absolute;top:-10px;left:35%;width:30%;height:22px;background:#aaa99b4d;z-index:1;transform:rotate(2deg)}.protokol .ed-id-photo{aspect-ratio:3/4;filter:grayscale(1)}.protokol .ed-evidence figcaption{font:400 12px/1.5 var(--ed-mono);text-align:center;margin-top:14px}.protokol .ed-evidence figcaption>span{text-transform:uppercase}.protokol .ed-evidence small{display:block;margin-top:6px;font-size:9px;color:#7d7a73}
.protokol .ed-names{margin:40px 0 22px;text-align:center;font-size:36px}.protokol .ed-ruling{border-block:1px solid var(--ed-line);padding:16px 0;margin-bottom:24px;text-align:center}.protokol .ed-ruling>p:first-child{text-transform:uppercase;font-weight:700}.protokol .ed-date{font:500 25px/1.2 var(--ed-script)!important;margin:14px 0 0}.protokol .ed-couple-proof{height:260px;margin-top:30px;filter:grayscale(1)}.protokol .ed-stamp{width:fit-content;max-width:100%;margin:26px auto 0;padding:12px 20px;border:3px double var(--ed-accent);font:700 16px/1.4 var(--ed-mono);color:var(--ed-accent);text-align:center;text-transform:uppercase;transform:rotate(-7deg)}
.protokol .ed-calendar .ed-selected{border:2px solid var(--ed-accent);border-radius:2px}.protokol .ed-calendar-paper{border:1px solid var(--ed-line);padding:20px}.protokol .ed-program h3{font:700 16px/1.6 var(--ed-mono)}.protokol .ed-program time{font:400 17px/1.6 var(--ed-mono)}.protokol .ed-program p{font-size:12px}.protokol .ed-palette{justify-content:flex-start}.protokol .ed-palette>span{border-radius:2px}.protokol .ed-countdown .vm-cd-num{font-family:var(--ed-mono);font-size:31px}.protokol .ed-countdown .vm-cd-cell{border:1px solid var(--ed-line)}.protokol .ed-intro-paper{background:#d3c5a8;min-height:240px;justify-content:space-between;transform:rotate(-4deg);border-radius:0 9px 9px 9px}.protokol .ed-intro-paper::before{content:'';position:absolute;top:-19px;left:-1px;width:44%;height:20px;background:#d3c5a8;border:1px solid var(--ed-line);border-bottom:0;border-radius:6px 6px 0 0}.protokol .ed-intro-paper>span{font:700 19px/1.4 var(--ed-mono);text-transform:uppercase}.protokol .ed-seal{border:3px double var(--ed-accent);padding:9px 24px;transform:rotate(-7deg)}.protokol .ed-intro-content>h2{font-family:var(--ed-mono);font-size:29px}.protokol .ed-intro-content>p{font-family:var(--ed-mono);font-size:13px}
@media(max-width:480px){.protokol .ed-heading{font-size:19px}.protokol .ed-document-subtitle{font-size:12px!important}.protokol .ed-evidence{width:84%}.protokol .ed-written{font-size:27px}.protokol .ed-section p{font-size:13px}.protokol .ed-countdown .vm-cd-num{font-size:26px}.protokol .ed-countdown .vm-cd-label{font-size:9px}}
`;

const POSTCARD = `
.sheet.postcard{--ed-paper:#f8f3e7;--ed-ink:#34454f;--ed-accent:#b7502f;--ed-line:#ddd4c3;--ed-body:var(--ed-sans);background-image:radial-gradient(#cfc6b8 1px,transparent 1px);background-size:66px 66px}
.postcard .ed-cover{padding-top:32px}.postcard .ed-post-kicker{font:600 26px/1.25 var(--ed-script);color:var(--ed-accent);margin-bottom:9px}.postcard .ed-names{font-size:46px;line-height:1.1}.postcard .ed-names i{color:#8fa8b7}.postcard .ed-date{font:500 17px/1.2 var(--ed-serif);background:var(--ed-accent);color:#fff6e5;border-radius:30px;padding:10px 24px;width:fit-content;margin:18px auto 0;box-shadow:0 7px 14px #b7502f22}
.postcard .ed-post-art{position:relative;width:100%;max-width:410px;margin:20px auto 14px}.postcard .ed-cover-image{aspect-ratio:4/5;overflow:visible}.postcard .ed-cover-image img{object-fit:contain}.postcard .ed-post-seal{position:absolute;bottom:13%;right:1%;display:grid;place-items:center;width:56px;height:56px;padding:6px;border-radius:50%;background:#9bb5c5;color:#fff8ed;font:500 23px/1.05 var(--ed-script);transform:rotate(10deg);box-shadow:0 5px 10px #34454f14;overflow-wrap:anywhere}
.postcard .ed-button,.postcard .ed-open{border-radius:30px}.postcard .ed-heading{color:var(--ed-accent);font-size:38px}.postcard .ed-note .ed-heading{font-family:var(--ed-script);font-size:40px}.postcard .ed-calendar-paper{background:#fffaf1;border-radius:8px;padding:20px;box-shadow:0 8px 22px #34454f0d;transform:rotate(-2deg)}.postcard .ed-calendar .ed-selected{background:var(--ed-accent);color:#fffaf1;border-color:var(--ed-accent)}
.postcard .ed-program time{font:600 31px/1.1 var(--ed-script)}.postcard .ed-venue-photo{border-radius:120px 120px 8px 8px}.postcard .ed-gallery figure{padding:9px 9px 14px;background:#fffaf1;box-shadow:0 8px 18px #34454f12;transform:rotate(-3deg)}.postcard .ed-gallery figure:nth-child(even){transform:rotate(3deg)}.postcard .ed-gallery figcaption{font:500 21px/1.15 var(--ed-script)}.postcard .ed-countdown .vm-cd-cell{border:0;background:#fffaf1;border-radius:8px;box-shadow:0 5px 10px #34454f0c}.postcard .ed-countdown .vm-cd-num{color:var(--ed-accent)}.postcard .ed-intro-paper{flex-direction:row;flex-wrap:wrap;background:#fffaf1;border:1px dashed #c5b79d;min-height:230px;padding:20px}.postcard .ed-intro-paper>span{font:600 30px/1.1 var(--ed-script);color:var(--ed-accent);flex:1}.postcard .ed-seal{flex-basis:100%;border-top:1px solid var(--ed-line);padding-top:12px}.postcard .ed-intro-art{width:150px;height:160px}
@media(max-width:480px){.postcard .ed-cover{padding:26px 20px 32px}.postcard .ed-post-kicker{font-size:24px}.postcard .ed-post-art{margin-top:12px}.postcard .ed-heading{font-size:34px}.postcard .ed-intro-art{width:130px;height:145px}}
`;

export const GAZETTE_CSS = BASE + GAZETTE;
export const PROTOKOL_CSS = BASE + PROTOKOL;
export const POSTCARD_CSS = BASE + POSTCARD;
