import type { Landing } from "../../types";

export const invitationsEn: Landing = {
  lang: "en",
  path: "/en/wedding-invitations",
  alternate: "/elektronnoe-priglashenie-na-svadbu",
  metaTitle: "Online Wedding Invitations with Personal Links — Vmeste",
  description: "Online wedding invitations with a personal link for every guest: 30+ designs, an inline editor, built-in RSVP, schedule, map and a gift list.",
  crumb: "Online wedding invitations",
  kicker: "Invitations",
  title: "Online wedding invitations with a personal link for every guest",
  lead:
    "An online wedding invitation is a web page your guests open from a link on their phone. In Vmeste you pick one of 30+ designs, add your own wording and photos, and every guest gets **their own link**: the invitation greets them by name, and they RSVP right there — attendance, plus-one, meal and drinks.",
  highlights: [
    "30+ designs, from classic to bold and playful",
    "A personal link that greets each guest by name",
    "RSVP, schedule, map, dress code and gift list on the same page",
    "Nothing to install — it opens in any browser",
  ],
  primary: { label: "Create your invitation", href: "/register?lang=en" },
  secondary: { label: "Browse designs", href: "/en#priglasheniya" },
  image: { src: "/media/feature-screens/invite.webp", alt: "An online wedding invitation in the “Love Confession” design", width: 1280, height: 720 },
  sections: [
    {
      kind: "cards",
      id: "whats-inside",
      kicker: "What’s inside",
      title: "One link instead of a card, a group chat and a spreadsheet",
      intro: "The invitation isn’t a picture — it’s a living page. Everything guests usually text you about is already in it.",
      cards: [
        { title: "A design that fits your day", text: "More than 30 templates with carefully chosen fonts, colours and animation. Change the wording and photos in the built-in editor — no designer needed." },
        { title: "Greets guests by name", text: "Every guest gets their own link, and the invitation addresses them by name. If you allow a plus-one, the guest adds their companion’s name in the RSVP form." },
        { title: "Built-in RSVP", text: "Attendance, plus-one, meal and drink choices, your own questions and song requests. See [online wedding RSVP](/en/wedding-rsvp) for details." },
        { title: "Schedule and map", text: "Arrival time, ceremony, reception, venue addresses with a map and the dress code — guests can pull up the invitation on the day and find everything themselves." },
        { title: "A gift list without duplicates", text: "Guests mark “I’ll get this one”, so nobody else picks the same gift. For cash gifts there’s an envelope with your payment details." },
        { title: "Check-in and seating", text: "On the day, guests scan a QR code at the entrance, type their name and see their table on the floor plan. See the [wedding seating chart](/en/wedding-seating-chart) page." },
      ],
    },
    {
      kind: "steps",
      id: "how-to",
      kicker: "How it works",
      title: "How to make an online wedding invitation",
      intro: "From an empty account to links sent out — in one evening.",
      steps: [
        { title: "Create your wedding", text: "Add your names, date and venue. They are filled into the invitation automatically." },
        { title: "Pick a design", text: "Browse the template catalogue and preview each one the way guests will see it, on a phone and on a laptop." },
        { title: "Write your wording", text: "Edit the greeting, schedule and details. Need a starting point? Use one of [30 wording examples](/en/blog/wedding-invitation-wording)." },
        { title: "Add your guests", text: "Type them in or import an Excel or CSV file. Every guest gets a personal link." },
        { title: "Send the links", text: "Copy each personal link and send it by text, messenger or email. Your dashboard shows who has opened the invitation and who has replied." },
      ],
    },
    {
      kind: "table",
      id: "comparison",
      kicker: "Comparison",
      title: "Online vs. paper invitations",
      intro: "It doesn’t have to be one or the other: many couples hand a printed card to their closest family and send everyone else a link.",
      head: ["", "Online", "Paper"],
      rows: [
        ["Delivery", "A link by text, messenger or email", "By hand or by post"],
        ["Changes after sending", "Edit once — guests see the new version", "Reprint or send a separate message"],
        ["Guest replies", "RSVP form inside the invitation", "A separate call, card or message"],
        ["Map, schedule, gifts", "On the same page", "On an insert card or a separate message"],
        ["Keepsake", "Stays a link", "Stays on the shelf"],
      ],
    },
    {
      kind: "text",
      id: "english-and-russian",
      kicker: "Language",
      title: "Invitations in English or Russian",
      paragraphs: [
        "Each wedding has its own language setting. Set it to English and the guest-facing pages — the invitation, RSVP form and check-in — are shown in English, with dates in English format.",
        "That makes Vmeste handy for international couples and destination weddings: you manage everything from one dashboard, and guests read the invitation in the language you chose.",
      ],
    },
  ],
  faq: [
    { q: "Do guests need to download an app or sign up?", a: "No. The invitation opens from a link in any browser — on a phone, tablet or computer. Guests don’t need an app or a password." },
    { q: "Can I change the invitation after sending it?", a: "Yes. Edits show up straight away on the same links, so if the arrival time or address changes you don’t need to send new invitations. It’s still worth messaging guests about important changes." },
    { q: "How do I send an online wedding invitation?", a: "Copy the guest’s personal link from your dashboard and send it however you like: text message, WhatsApp, Telegram or email. The link works the same everywhere." },
    { q: "Can a guest bring a plus-one?", a: "Yes. Mark the guest as allowed a plus-one and the RSVP form will ask for their companion’s name. The companion is added to your guest list and can be seated like anyone else." },
    { q: "Can I print the invitation too?", a: "Yes. Besides the online page, the dashboard has a print editor that builds your invitation as a PDF for anyone who prefers paper. The RSVP form stays online." },
    { q: "What happens to the invitation after the wedding?", a: "Ten days after the wedding the event is archived and guest links stop working. Your guest list and RSVPs stay in your dashboard." },
  ],
  articles: ["wedding-invitation-wording", "how-to-collect-wedding-rsvps-online", "how-to-make-a-wedding-seating-chart"],
  final: { title: "Make your invitation tonight", text: "Pick a design, add your wording, and every guest gets a personal link with an RSVP form." },
};
