export const SCRAPBOOK_FONTS_LINK = '<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&family=Comfortaa:wght@400;500;600;700&family=Marck+Script&display=swap" rel="stylesheet">';

const COMMON = `
.sheet.zefir,.sheet.crayon{--sb-ink:#493d38;--sb-accent:#b96583;--sb-blue:#a8c6d7;--sb-yellow:#edcb78;--sb-serif:'Marck Script',cursive;--sb-sans:'Comfortaa',sans-serif;--sb-script:'Caveat',cursive;max-width:720px;padding:0;color:var(--sb-ink);font:15px/1.8 var(--sb-sans);isolation:isolate;box-shadow:none;overflow:hidden}
.sb-section{position:relative;padding:56px clamp(22px,6vw,64px);text-align:center;border:0;min-width:0}
.sb-section h1,.sb-section h2,.sb-section h3,.sb-section p{max-width:100%;overflow-wrap:anywhere}
.sb-section h2{font:500 clamp(34px,8vw,46px)/1.12 var(--sb-script);letter-spacing:0;text-transform:none;margin:0 0 24px;color:var(--sb-accent)}
.sb-section h2::after{display:none}.sb-section h3{font:600 17px/1.5 var(--sb-sans);margin:12px 0 8px;text-transform:none;letter-spacing:0}
.sb-section p{margin:14px auto;max-width:480px}.sb-section .sb-hand,.sb-photo-note,.sb-section figcaption{font:500 24px/1.2 var(--sb-script)}
.sb-section figure{margin:0;min-width:0}.sb-photo{position:relative;overflow:hidden;min-width:0}.sb-photo img{display:block;max-width:100%;width:100%;height:100%;object-fit:cover;margin:0}
.sb-doodle{width:46px;height:46px;color:var(--sb-accent);flex-shrink:0}.sb-star{color:var(--sb-yellow)}
.sb-cover{padding-top:32px;padding-bottom:38px}.sb-cover-title{position:relative;margin:0 auto 30px;max-width:440px}.sb-cover-title p{font:600 clamp(28px,7vw,40px)/1.1 var(--sb-script);color:var(--sb-accent);margin:0}.sb-cover-title>.sb-star{position:absolute;width:28px;right:-8px;top:-12px}
.sb-hero-frame{position:relative;max-width:430px;width:91%;padding:11px 11px 32px;margin:0 auto 26px;transform:rotate(-3deg);background:#fffdfa;box-shadow:0 12px 30px #493d3819}
.sb-hero-photo{height:clamp(265px,67vw,440px)}.sb-hero-frame::before{content:'';position:absolute;z-index:2;width:30%;height:28px;top:-14px;left:34%;background:#e3cdbbb3;transform:rotate(5deg);clip-path:polygon(3% 0,98% 3%,96% 100%,0 95%)}
.sb-hero-frame>.sb-heart{position:absolute;right:-17px;bottom:0;width:52px;transform:rotate(15deg)}.sb-photo-note{display:block;position:absolute;left:20px;bottom:6px;color:var(--sb-accent);font-size:22px}
.sb-cover-heading{margin:0 auto 18px}.sb-cover-heading .sb-names{display:block;margin:0 auto 10px;font:600 clamp(32px,8vw,48px)/1.12 var(--sb-script);text-transform:none;letter-spacing:0;color:var(--sb-accent);overflow-wrap:anywhere}.sb-names i{font-style:normal;color:var(--sb-blue)}
.sb-cover-heading .sb-date{display:inline-block;margin:0;padding:5px 20px;border:1px solid var(--sb-accent);border-radius:999px;font:500 23px/1.2 var(--sb-script);color:var(--sb-accent)}
.sb-childhood{position:relative;margin:38px auto 0;max-width:440px}.sb-child-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;padding:20px 8px}.sb-child-grid .sb-child{position:relative;padding:9px 9px 15px;transform:rotate(-6deg);background:#fefcf8;box-shadow:0 8px 22px #493d381a}.sb-child-grid .sb-child:nth-child(even){transform:rotate(5deg)}.sb-child .sb-photo{height:clamp(140px,38vw,235px)}.sb-child figcaption{margin:12px 0 0;color:var(--sb-accent);font-size:20px}.sb-childhood>.sb-flower{position:absolute;right:-8px;bottom:-10px;width:55px;color:var(--sb-yellow)}
.sb-calendar-paper{position:relative;max-width:360px;margin:30px auto;padding:24px 18px;background:#fffdfa;box-shadow:0 8px 20px #493d3810;transform:rotate(2deg)}.sb-calendar-paper::before{content:'';position:absolute;top:-10px;left:35%;width:30%;height:25px;background:#d3e0d2b3;transform:rotate(-4deg)}.sb-calendar-paper .sb-month{font:600 25px/1.2 var(--sb-script);color:var(--sb-accent);margin:0 0 18px;text-transform:capitalize}
.sb-calendar{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));row-gap:9px;align-items:center;font-size:14px;line-height:2.4}.sb-calendar>span{position:relative;min-width:0}.sb-calendar .sb-weekday{font-size:11px;color:#87736d}.sb-selected{font-weight:700;color:var(--sb-accent)}.sb-selected>.sb-heart{position:absolute;inset:-4px;width:calc(100% + 8px);height:calc(100% + 8px);stroke-width:1.5}
.sb-countdown .vm-cd-cell{border:0;border-radius:1px;background:#fffdfa;box-shadow:0 6px 13px #493d3810;transform:rotate(-3deg);padding:18px 1px}.sb-countdown .vm-cd-cell:nth-child(even){transform:rotate(3deg);background:#f1e3e9}.sb-countdown .vm-cd-cell::after{display:none}.sb-countdown .vm-cd-cell b{font-family:var(--sb-script);color:var(--sb-accent);font-size:clamp(30px,9vw,48px)}.sb-countdown .vm-cd-cell span{font-family:var(--sb-sans);letter-spacing:0;font-size:10px}.sb-countdown>.sb-star{margin-top:20px;width:30px}
.sb-timeline ol{list-style:none;margin:30px auto 0;padding:0;max-width:470px;text-align:left}.sb-timeline li{position:relative;display:grid;grid-template-columns:42px 65px 1fr;align-items:start;gap:15px;padding:16px 0;border-bottom:1px dashed #e4d6c8}.sb-timeline li:last-child{border:0}.sb-timeline li>.sb-doodle{width:36px;height:40px}.sb-timeline time{font:600 28px/1.2 var(--sb-script);color:var(--sb-accent)}.sb-timeline li h3{font-size:15px;margin:0}.sb-timeline li p{font-size:12px;line-height:1.7;margin:7px 0 0}.sb-timing-icon{height:36px;width:36px}
.sb-button,.sb-add{display:inline-flex;justify-content:center;align-items:center;gap:7px;min-height:46px;max-width:100%;margin:15px 5px 0;padding:10px 22px;background:var(--sb-accent);color:#fffdfa;border:0;border-radius:2px;font:500 13px/1.5 var(--sb-sans);text-decoration:none;cursor:pointer;overflow-wrap:anywhere}
.sb-venue-photo{height:clamp(210px,55vw,360px);border:10px solid #fffdfa;box-shadow:0 8px 22px #493d3812;margin:20px 0 26px;transform:rotate(-2deg)}.sb-section .venue-map{height:230px;border:7px solid #fffdfa;border-radius:0;transform:rotate(1deg);box-shadow:0 8px 22px #493d3812}.sb-map .sb-button{background:transparent;color:var(--sb-accent);border:1px solid currentColor}
.sb-dresscode>.sb-flower{width:54px;margin-bottom:18px;color:var(--sb-accent)}.sb-palette{display:flex;justify-content:center;flex-wrap:wrap;gap:13px;margin:30px auto}.sb-palette>span{display:block;width:51px;height:61px;border-radius:50% 40% 45% 38%;transform:rotate(-12deg);box-shadow:inset 3px 3px 6px #fffdfa50}.sb-palette>span:nth-child(even){transform:rotate(13deg);border-radius:38% 50% 38% 50%}.sb-outfits{height:260px;border:8px solid #fffdfa;max-width:400px;margin:25px auto 0}
.sb-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px 18px;max-width:490px;margin:30px auto 0;padding:12px 8px}.sb-gallery figure{padding:9px 9px 18px;background:#fffdfa;box-shadow:0 10px 22px #493d3812;transform:rotate(-4deg)}.sb-gallery figure:nth-child(even){transform:rotate(4deg)}.sb-gallery .sb-photo{height:clamp(150px,42vw,255px)}.sb-gallery figcaption{font-size:20px;margin-top:12px;color:var(--sb-accent)}
.sb-note{margin:22px;background:#fffdfa;box-shadow:0 8px 22px #493d380c;transform:rotate(-1deg);padding:40px 22px}.sb-note::before{content:'';position:absolute;width:90px;height:26px;left:calc(50% - 45px);top:-12px;background:#e3cdbb99;transform:rotate(5deg)}.sb-note>.sb-heart{margin:18px auto 0;width:35px}.sb-wishlist{background:#f1e3e9}.sb-rsvp{background:#f4e9df}.sb-rsvp .vm-rsvp{max-width:440px;font-size:13px}.sb-rsvp .vm-rsvp input[type=text]{background:#fffdfa;border:1px solid #d9c3b5;border-radius:2px;font:inherit;color:var(--sb-ink)}.sb-rsvp .vm-rsvp-submit{background:var(--sb-accent);color:#fffdfa;border:0;border-radius:2px}.sb-rsvp .vm-rsvp-choice input{accent-color:var(--sb-accent)}
.sb-intro[hidden]{display:none!important}.sb-intro{position:fixed;z-index:1000;inset:0;overflow-y:auto;overscroll-behavior:contain;background:var(--sb-paper,#faf4ef);display:grid;place-items:center;padding:30px 22px}.sb-intro-card{width:min(100%,410px);padding:30px 18px;text-align:center}.sb-intro-card h2{font-size:38px;margin-bottom:12px}.sb-intro-card p{font:500 22px/1.3 var(--sb-script);margin-bottom:25px}.sb-intro-pair{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:32px 0;align-items:center}.sb-intro-pair>figure{margin:0;padding:8px 8px 17px;background:#a8c6d7;transform:rotate(-6deg);box-shadow:0 8px 18px #493d3819}.sb-intro-pair .sb-photo{height:210px}.sb-intro-pair figcaption{font-size:21px;margin-top:9px}
.sb-flip{position:relative;display:block;border:0;padding:0;background:transparent;width:100%;height:260px;cursor:pointer;perspective:900px;color:var(--sb-ink);font:600 26px/1.2 var(--sb-script);transform:rotate(5deg)}.sb-flip-front,.sb-flip-back{position:absolute;inset:0;backface-visibility:hidden;transition:transform .7s;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:10px;background:#c787a0;border-radius:12px;box-shadow:0 8px 18px #493d3819}.sb-flip-front>.sb-heart{width:80px;height:80px;color:#fffdfa;margin-bottom:20px}.sb-flip-back{transform:rotateY(180deg);background:#fefcf8}.sb-flip-back .sb-photo{width:100%;height:205px;margin-bottom:9px}.sb-flipped .sb-flip-front{transform:rotateY(180deg)}.sb-flipped .sb-flip-back{transform:rotateY(360deg)}.sb-open{border:1px solid var(--sb-accent);color:#fffdfa;background:var(--sb-accent);padding:14px 25px;max-width:100%;font:500 14px/1.5 var(--sb-sans);cursor:pointer;border-radius:999px}
.sb-envelope{position:relative;margin:70px auto 55px;height:170px;max-width:300px;background:#e9d5bf;box-shadow:0 14px 28px #493d3820;border-radius:3px}.sb-envelope::before{content:'';position:absolute;inset:0;background:#f1e3ce;clip-path:polygon(0 0,50% 65%,100% 0)}.sb-envelope>.sb-heart{position:absolute;left:40%;top:30%;width:20%;height:40%}.sb-seal{position:absolute;left:0;right:0;bottom:12px;font:600 26px var(--sb-script);color:var(--sb-accent)}.sb-intro-settings{background:#fffdfa;padding:10px;margin-bottom:20px}.sb-music-toggle{position:fixed;z-index:70;bottom:18px;right:18px;min-height:44px;padding:9px 13px;max-width:160px;border:1px solid var(--sb-accent);background:#fffdfa;color:var(--sb-accent);border-radius:999px;font:12px var(--sb-sans);cursor:pointer}.sb-music-toggle[aria-pressed=true]{background:var(--sb-accent);color:#fffdfa}
@media(max-width:430px){.sb-section{padding:40px 24px}.sb-cover{padding-top:28px}.sb-cover-title{margin-bottom:24px}.sb-cover-title p{font-size:29px}.sb-cover-heading .sb-names{font-size:37px}.sb-hero-frame{margin-bottom:20px;width:94%}.sb-cover>p{font-size:12px;line-height:1.85}.sb-timeline li{grid-template-columns:32px 51px 1fr;gap:10px}.sb-timeline li>.sb-doodle{width:28px}.sb-timeline time{font-size:25px}.sb-timeline li h3{font-size:13px}.sb-note{padding:35px 20px}.sb-section h2{font-size:35px}.sb-intro-pair .sb-photo{height:180px}.sb-flip{height:240px}.sb-flip-back .sb-photo{height:190px}.sb-rsvp .vm-rsvp{font-size:12px}.sb-gallery figcaption{font-size:19px}.sb-cover-heading{max-width:100%}}
@media(prefers-reduced-motion:reduce){.sb-flip-front,.sb-flip-back{transition:none}.sb-section{scroll-behavior:auto}}
`;

export const ZEFIR_CSS = COMMON + `
.sheet.zefir{--sb-paper:#faf4ef;background:#faf4ef;background-image:radial-gradient(ellipse at 16px 20px,#c787a014 2px,transparent 3px),radial-gradient(ellipse at 48px 50px,#a8c6d714 2px,transparent 3px);background-size:65px 70px}
.zefir .sb-cover-title p{font-family:var(--sb-serif);font-weight:400;font-size:clamp(31px,8vw,46px)}.zefir .sb-child::before{content:'';position:absolute;z-index:2;width:45%;height:20px;left:27%;top:-8px;background:#a8c6d799;transform:rotate(4deg)}.zefir .sb-child:nth-child(even)::before{background:#c787a066}.zefir .sb-date-section{background:#f1e3e966;clip-path:polygon(0 1%,12% 0,35% 2%,55% 0,72% 1%,100% 0,100% 99%,82% 100%,65% 98%,44% 100%,20% 99%,0 100%)}.zefir .sb-countdown{padding-top:35px}.zefir .sb-rsvp{background:#eaeedf}.zefir .sb-dresscode{background:#f5ede5}
`;

export const CRAYON_CSS = COMMON + `
.crayon .sb-intro-card{width:min(100%,540px);padding:22px 0}.crayon .sb-intro-card h2{font-size:clamp(35px,7vw,44px)}.crayon .sb-envelope.sb-envelope-art{width:100%;max-width:520px;height:auto;margin:30px auto 22px;background:transparent;border:0;border-radius:0;box-shadow:none;transform:none}.crayon .sb-envelope-art::before{display:none}.crayon .sb-envelope-art>img{display:block;width:100%;height:auto;margin:0;object-fit:contain}.crayon .sb-envelope-art .sb-seal{left:57%;right:auto;top:75%;bottom:auto;width:38%;transform:translate(-50%,-50%) rotate(-5deg);font:500 clamp(20px,6vw,30px)/1.1 var(--sb-script);overflow-wrap:anywhere;color:#ad5578}.crayon .sb-intro .sb-open{border-radius:999px;transform:none;padding:15px 28px;box-shadow:0 7px 20px #ad55781a}
.sheet.crayon{--sb-paper:#fffbed;--sb-accent:#ad5578;background:#fffbed}.crayon .sb-cover-title p{font-family:var(--sb-sans);font-weight:700;text-transform:uppercase;font-size:clamp(24px,6vw,32px);line-height:1.4;color:#edcb78;text-shadow:1px 1px 0 #b8873b,-1px -1px 0 #b8873b;transform:rotate(-1deg)}.crayon .sb-cover-title>.sb-star{right:-14px;top:40px}.crayon .sb-cover-heading .sb-names{font-family:var(--sb-sans);font-size:clamp(25px,6vw,38px);font-weight:700}.crayon .sb-cover-heading .sb-date{border:0;font-family:var(--sb-script);font-size:29px;color:#b8873b}.crayon .sb-hero-frame::before{display:none}.crayon .sb-hero-frame>.sb-heart{color:#ad5578;right:-15px;bottom:10px}.crayon .sb-section h2{font-weight:700}.crayon .sb-child-grid .sb-child{box-shadow:none;background:#a8c6d7;border-radius:5px}.crayon .sb-child-grid .sb-child:nth-child(even){background:#e9c4d2}.crayon .sb-child-grid figcaption{color:#493d38}.crayon .sb-calendar-paper{background:transparent;box-shadow:none;transform:rotate(-1deg)}.crayon .sb-calendar-paper::before{display:none}.crayon .sb-calendar{row-gap:13px}.crayon .sb-selected>.sb-heart{stroke-width:3}.crayon .sb-timeline li{border-bottom:2px dotted #e4d6c8}.crayon .sb-timeline li:nth-child(2n)>.sb-doodle{color:#a2b29c}.crayon .sb-timeline li:nth-child(3n)>.sb-doodle{color:#b8873b}.crayon .sb-palette>span{border-radius:40% 50% 45% 35%}.crayon .sb-rsvp{background:#f5f1dc;border-top:2px dashed #edcb78;border-bottom:2px dashed #edcb78}.crayon .sb-wishlist{background:#eaf0e5}.crayon .sb-note{background:#fffdfa;box-shadow:none;border:2px dashed #e4d6c8}.crayon .sb-countdown .vm-cd-cell{background:#e7edf2;border:1px dashed #a8c6d7;box-shadow:none;border-radius:6px}.crayon .sb-countdown .vm-cd-cell:nth-child(even){background:#f6e9ed;border-color:#c787a0}.crayon .sb-button{border-radius:40% 35% 30% 25% / 10% 20% 15% 15%}.crayon .sb-envelope{background:#a8c6d7;border:2px dashed #87736d;transform:rotate(-5deg)}.crayon .sb-envelope::before{background:#dce7ed}.crayon .sb-open{border-radius:4px;transform:rotate(1deg)}
`;
