export const EVERGREEN_CSS = `
body{background:#111812;color:var(--fg);font-size:17px;background-image:radial-gradient(circle at 15% 10%,#34463855,transparent 34%),radial-gradient(circle at 88% 55%,#25332966,transparent 38%),repeating-linear-gradient(120deg,#ffffff05 0 1px,transparent 1px 5px)}
.sheet.evergreen{max-width:38rem;background:var(--card);box-shadow:0 24px 100px #0008;overflow:hidden}
.evergreen [data-evergreen-block]{position:relative;margin:0;padding:4.5rem 2.5rem;overflow:hidden}.evergreen [data-evergreen-block]>*:not(.eg-scroll-vine):not(.eg-edit-badge){position:relative;z-index:1}
.evergreen .eg-cover{min-height:96svh;padding:0;display:flex;align-items:flex-end;color:#fff;background:#101710}
.eg-cover-media{position:absolute!important;z-index:0!important;inset:0;overflow:hidden}.eg-cover-media img{position:absolute;left:0;top:-6%;width:100%;height:112%;object-fit:cover;object-position:center 35%;display:block;transform:translate3d(0,var(--eg-parallax,0px),0) scale(1.055);will-change:transform}.eg-cover-media::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,#10171018 20%,#10171080 63%,#101710f5 100%),linear-gradient(90deg,#10171022,#10171000)}
.eg-cover-media .ie-image-placeholder{position:absolute;inset:1rem;height:calc(100% - 2rem);z-index:1;background:#172018!important;color:#dcc28f!important}
.eg-cover-copy{position:relative;z-index:2;width:100%;padding:7rem 2.4rem 3.2rem;text-align:left}.eg-eyebrow,.eg-date{margin:0;font:500 .64rem/1.7 var(--sans);letter-spacing:.26em;text-transform:uppercase;color:#dcc28f}.evergreen .eg-names{margin:.9rem 0 1.3rem;font:400 clamp(3.5rem,13vw,5.35rem)/.88 var(--serif);letter-spacing:-.055em;text-transform:none;color:#fff;max-width:10ch}.eg-names .eg-person{display:block}.eg-names .eg-amp{display:inline;color:#c4a264;font-style:italic;font-size:.72em;padding-right:.04em}.eg-cover-subtitle{max-width:25rem;margin:1.4rem 0 0;font-size:.78rem;line-height:1.8;letter-spacing:.13em;text-transform:uppercase;color:#eee7dc}.eg-gold-line{display:block;width:2.8rem;height:1px;margin:1.5rem 0;background:#c4a264}
.eg-cover-mark{position:absolute!important;z-index:2!important;width:7.5rem;height:7.5rem;right:1.2rem;top:1.2rem;color:#d7b779;opacity:.72;animation:eg-orbit 18s linear infinite}.eg-cover-mark circle,.eg-cover-mark path{stroke:currentColor;stroke-width:.7}.eg-mark-orbit{stroke-dasharray:3 4}.eg-mark-delay{animation:eg-orbit-reverse 12s linear infinite;transform-origin:50% 50%}.eg-mark-spark{opacity:.55}
.eg-fireflies{position:absolute!important;inset:0;z-index:1!important;pointer-events:none}.eg-fireflies i{position:absolute;width:3px;height:3px;border-radius:50%;background:#f7daa0;box-shadow:0 0 12px 4px #efc46c88;opacity:0;animation:eg-firefly 7s ease-in-out infinite}.eg-fireflies i:nth-child(1){left:13%;top:24%}.eg-fireflies i:nth-child(2){left:76%;top:18%;animation-delay:1.1s}.eg-fireflies i:nth-child(3){left:62%;top:43%;animation-delay:2.8s}.eg-fireflies i:nth-child(4){left:88%;top:62%;animation-delay:4s}.eg-fireflies i:nth-child(5){left:24%;top:58%;animation-delay:.7s}.eg-fireflies i:nth-child(6){left:45%;top:12%;animation-delay:3.4s}.eg-fireflies i:nth-child(7){left:8%;top:75%;animation-delay:5.2s}.eg-fireflies i:nth-child(8){left:70%;top:77%;animation-delay:1.8s}.eg-fireflies i:nth-child(9){left:38%;top:68%;animation-delay:4.6s}
.eg-scroll-cue{position:absolute!important;z-index:3!important;right:1.6rem;bottom:2.2rem;display:flex;flex-direction:column;align-items:center;gap:.55rem;color:#fff9}.eg-scroll-cue span{width:1px;height:3rem;background:linear-gradient(#d7b779,transparent);transform-origin:top;animation:eg-scroll-line 2.4s ease-in-out infinite}.eg-scroll-cue small{font:500 .5rem var(--sans);letter-spacing:.2em;text-transform:uppercase;writing-mode:vertical-rl}
.evergreen .eg-intro{text-align:center;background:#f4f0e8;padding-top:5.5rem;padding-bottom:5.5rem}.eg-intro h2,.eg-location h2,.eg-section-title{font:400 clamp(2rem,7vw,2.8rem)/1.15 var(--serif);letter-spacing:-.025em;text-transform:none;margin:0 auto 1.5rem;max-width:14ch}.eg-intro .eg-copy{max-width:27rem;margin:0 auto;color:var(--muted);line-height:1.9;white-space:pre-line}
.evergreen .eg-gallery{padding:0;background:#172018;color:#f4f0e8}.eg-location-head{padding:4rem 2.5rem 2.1rem;text-align:center}.eg-location-head h2{color:#f4f0e8;margin-bottom:0}.eg-photo{position:relative;margin:0;min-height:28rem;overflow:hidden;clip-path:inset(0 0 100% 0);transition:clip-path 1.4s cubic-bezier(.22,.75,.22,1)}.eg-in .eg-photo{clip-path:inset(0)}.eg-photo img{display:block;width:100%;height:112%;min-height:28rem;object-fit:cover;position:absolute;left:0;top:-6%;transform:translate3d(0,var(--eg-parallax,0px),0) scale(1.04);will-change:transform}.eg-photo::after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,#111812cc 0,transparent 48%)}.eg-photo figcaption{position:absolute;z-index:2;left:2rem;right:2rem;bottom:2rem;text-align:left;color:#fff;font:.72rem/1.7 var(--sans);letter-spacing:.18em;text-transform:uppercase}.eg-photo-number{position:absolute;z-index:2;right:1.3rem;top:1.3rem;color:#fff9;font:italic 1rem var(--serif);letter-spacing:.08em}
.eg-gallery-mosaic{background:#101710;padding-bottom:4.5rem!important}.eg-gallery-mosaic .eg-location-head{padding-bottom:2.8rem}.eg-mosaic{display:grid;grid-template-columns:1.08fr .92fr;grid-template-rows:19rem 19rem;gap:.65rem;padding:0 .65rem}.eg-mosaic .eg-photo{min-height:0}.eg-mosaic .eg-photo img{min-height:0}.eg-mosaic .eg-photo:first-child{grid-row:1/3}.eg-mosaic .eg-photo figcaption{left:.75rem;right:.75rem;bottom:.9rem;font-size:.58rem;letter-spacing:.06em;hyphens:auto;overflow-wrap:break-word}.eg-mosaic .eg-photo-number{top:.8rem;right:.8rem;font-size:.75rem}
.evergreen .eg-venue{background:#f4f0e8;text-align:left;padding-top:3.6rem;padding-bottom:3.6rem}.eg-label{font:.62rem/1.4 var(--sans);letter-spacing:.24em;text-transform:uppercase;color:var(--accent);margin:0 0 .7rem}.eg-venue h2{font:400 2.15rem/1.15 var(--serif);margin:0 0 .8rem;text-align:left}.eg-address{margin:0;color:var(--muted);font:.72rem/1.7 var(--sans);letter-spacing:.14em;text-transform:uppercase}.eg-note{margin:1.7rem 0 0;padding-top:1.5rem;border-top:1px solid var(--line);line-height:1.8;white-space:pre-line}
.evergreen .eg-timeline{background:#ebe5da;text-align:left}.eg-timeline .eg-section-title{text-align:left;margin-left:0}.eg-schedule{list-style:none;padding:0 0 0 1.4rem;margin:2.5rem 0 0;position:relative}.eg-schedule::before{content:'';position:absolute;left:.22rem;top:.7rem;bottom:.7rem;width:1px;background:var(--accent);transform:scaleY(0);transform-origin:top;transition:transform 1.7s .25s cubic-bezier(.22,.75,.22,1)}.eg-in .eg-schedule::before{transform:scaleY(1)}.eg-schedule li{display:grid;grid-template-columns:4.3rem 1fr;gap:1.2rem;padding:1.15rem 0;border-top:1px solid #cfc5b5;position:relative;opacity:0;transform:translateX(18px);transition:.7s ease}.eg-schedule li::before{content:'';position:absolute;left:-1.43rem;top:1.55rem;width:.5rem;height:.5rem;border-radius:50%;background:#ebe5da;border:1px solid var(--accent);transform:scale(0);transition:transform .5s}.eg-in .eg-schedule li{opacity:1;transform:none}.eg-in .eg-schedule li::before{transform:scale(1)}.eg-in .eg-schedule li:nth-child(2){transition-delay:.12s}.eg-in .eg-schedule li:nth-child(3){transition-delay:.24s}.eg-in .eg-schedule li:nth-child(4){transition-delay:.36s}.eg-schedule time{font:italic 1rem/1.4 var(--serif);color:var(--leaf)}.eg-schedule strong{display:block;font-weight:400;font-size:1.1rem}.eg-schedule small{display:block;margin-top:.2rem;color:var(--muted);font-size:.8rem}
.eg-journey-rings{position:fixed!important;z-index:70!important;inset:0;overflow:hidden;pointer-events:none}.eg-journey-ring{position:absolute!important;left:50%;top:0;width:clamp(4.3rem,13vw,6.8rem);height:auto;opacity:var(--eg-ring-opacity,0);transform:translate3d(calc(-50% + var(--eg-ring-x,0px)),var(--eg-ring-y,-120px),0) rotate(var(--eg-ring-spin,0deg)) rotateX(var(--eg-ring-tilt,0deg)) scale(var(--eg-ring-scale,.65));filter:drop-shadow(0 12px 13px #2b1b1266) drop-shadow(0 0 12px #e8c78055);will-change:transform,opacity}.eg-ring-two{z-index:2;filter:drop-shadow(0 14px 15px #2b1b1270) drop-shadow(0 0 15px #efd99a66)}.eg-add-detail{display:block;margin:2rem auto 0;border:1px dashed #9c825a;background:#f4f0e8;color:#493d2b;padding:.8rem 1.1rem;border-radius:999px;font:600 .72rem var(--sans);letter-spacing:.06em;cursor:pointer;transition:background .2s,transform .2s}.eg-add-detail:hover{background:#fff;transform:translateY(-2px)}
.evergreen .eg-dress{background:#172018;color:#f2ede5;text-align:center}.eg-dress .eg-section-title{color:#fff}.eg-dress-copy{max-width:25rem;margin:0 auto;color:#c9c6bc;line-height:1.85;white-space:pre-line}.eg-palette{display:flex;justify-content:center;gap:.7rem;margin-top:2.2rem}.eg-palette i{display:block;width:2.65rem;height:2.65rem;border-radius:50%;border:1px solid #ffffff44;box-shadow:0 5px 20px #0004;opacity:0;transform:translateY(18px) scale(.8);transition:.65s ease}.eg-in .eg-palette i{opacity:1;transform:none}.eg-in .eg-palette i:nth-child(2){transition-delay:.1s}.eg-in .eg-palette i:nth-child(3){transition-delay:.2s}.eg-in .eg-palette i:nth-child(4){transition-delay:.3s}.eg-in .eg-palette i:nth-child(5){transition-delay:.4s}
.evergreen .eg-rsvp{text-align:center;background:#f4f0e8}.eg-rsvp .eg-copy{max-width:25rem;margin:0 auto;color:var(--muted);line-height:1.85;white-space:pre-line}.eg-rsvp .cta{position:relative;overflow:hidden;margin-top:2rem;display:inline-flex;min-height:3.4rem;align-items:center;padding:0 2rem;background:#1b2b20;color:#fff;border-radius:.2rem;font:500 .72rem var(--sans);letter-spacing:.13em;text-transform:uppercase}.eg-rsvp .cta::before{content:'';position:absolute;inset:0;background:linear-gradient(105deg,transparent 35%,#fff4 50%,transparent 65%);transform:translateX(-120%);animation:eg-shine 4.5s 2s ease-in-out infinite}
.evergreen .eg-closing{text-align:center;min-height:30rem;display:flex;flex-direction:column;justify-content:center;background:linear-gradient(#172018e8,#172018f5),url('/media/invite-evergreen/dinner.webp') center/cover;color:#f4f0e8;background-attachment:fixed}.eg-closing h2{color:#fff}.eg-closing .eg-copy{max-width:24rem;margin:0 auto;color:#cec8bc;white-space:pre-line}.eg-closing .eg-gold-line{margin:1.8rem auto}.evergreen .foot{background:#111812;color:#a9aa9d;padding:1.5rem;text-align:center;font:.65rem var(--sans);letter-spacing:.12em}
.eg-scroll-vine{position:absolute;z-index:0;left:-2.5rem;top:8%;width:9.5rem;height:84%;color:var(--accent);opacity:.2;pointer-events:none}.eg-vine-right{left:auto;right:-2.5rem;transform:scaleX(-1)}.eg-scroll-vine path{stroke:currentColor;stroke-width:1;vector-effect:non-scaling-stroke}.eg-vine-leaves path{fill:currentColor;stroke:none;opacity:0;transform:scale(.7);transform-origin:center;transition:opacity .65s,transform .8s}.eg-vine-line{stroke-dasharray:1;stroke-dashoffset:1}.eg-in .eg-vine-line{animation:eg-draw 2.2s .15s ease-out forwards}.eg-in .eg-vine-leaves path{opacity:.8;transform:scale(1)}.eg-in .eg-vine-leaves path:nth-child(2){transition-delay:.25s}.eg-in .eg-vine-leaves path:nth-child(3){transition-delay:.45s}.eg-in .eg-vine-leaves path:nth-child(4){transition-delay:.65s}.eg-in .eg-vine-leaves path:nth-child(5){transition-delay:.85s}
.eg-progress{position:fixed!important;z-index:80!important;left:0;right:0;top:0;height:3px;background:#ffffff12;pointer-events:none}.eg-progress i{display:block;width:100%;height:100%;background:linear-gradient(90deg,#8c6a36,#e6c98e);transform:scaleX(0);transform-origin:left;will-change:transform;box-shadow:0 0 14px #d7b77988}
.eg-motion .evergreen [data-evergreen-block]{opacity:0;transform:translateY(28px);transition:opacity 1s ease,transform 1s ease}.eg-motion .evergreen [data-evergreen-block].eg-in{opacity:1;transform:none}.eg-motion .evergreen .eg-cover{opacity:1;transform:none}.eg-motion .evergreen h2,.eg-motion .evergreen .eg-section-title{transform:translateY(22px);opacity:0;transition:transform .9s .16s ease,opacity .9s .16s ease}.eg-motion .evergreen .eg-in h2,.eg-motion .evergreen .eg-in .eg-section-title{transform:none;opacity:1}
@keyframes eg-draw{to{stroke-dashoffset:0}}@keyframes eg-orbit{to{transform:rotate(360deg)}}@keyframes eg-orbit-reverse{to{transform:rotate(-360deg)}}@keyframes eg-firefly{0%,100%{opacity:0;transform:translate(0,8px) scale(.5)}35%{opacity:.9}60%{opacity:.2;transform:translate(14px,-18px) scale(1.2)}}@keyframes eg-scroll-line{0%,100%{transform:scaleY(.25);opacity:.3}50%{transform:scaleY(1);opacity:1}}@keyframes eg-shine{0%,60%{transform:translateX(-120%)}85%,100%{transform:translateX(120%)}}
.evergreen .eg-venue h2::after,.evergreen .eg-timeline h2::after{margin-left:0}
.evergreen h2:has(+.eg-gold-line)::after{display:none}
@media(max-width:520px){.eg-mosaic{grid-template-columns:1fr;grid-template-rows:none}.eg-mosaic .eg-photo,.eg-mosaic .eg-photo:first-child{grid-row:auto;min-height:25rem}.eg-closing{background-attachment:scroll!important}}
@media(max-width:390px){.evergreen [data-evergreen-block]{padding-left:1.5rem;padding-right:1.5rem}.eg-cover-copy{padding-left:1.5rem;padding-right:1.5rem}.eg-location-head{padding-left:1.5rem;padding-right:1.5rem}.eg-palette{gap:.45rem;flex-wrap:wrap}.eg-palette i{width:2.3rem;height:2.3rem}.eg-cover-mark{width:5.6rem;height:5.6rem}.eg-scroll-cue{right:.8rem}.eg-scroll-vine{opacity:.12}}
@media(prefers-reduced-motion:reduce){.eg-motion .evergreen [data-evergreen-block],.eg-motion .evergreen h2,.eg-motion .evergreen .eg-section-title,.eg-schedule li{opacity:1;transform:none;transition:none}.eg-photo{clip-path:none}.eg-photo img,.eg-cover-media img{transition:none;transform:none}.eg-fireflies,.eg-scroll-cue,.eg-journey-rings{display:none}.eg-cover-mark{animation:none}.eg-vine-line{stroke-dashoffset:0}.eg-vine-leaves path{opacity:.8;transform:none}.eg-schedule::before{transform:scaleY(1)}.eg-palette i{opacity:1;transform:none}.eg-rsvp .cta::before{display:none}}
`.replace(/\n/g, "");

export const EVERGREEN_EDITOR_CSS = `
html.eg-editing body{padding:0;background:#263228}.eg-editing .sheet.evergreen{box-shadow:none}.eg-editing .evergreen [data-evergreen-block],.eg-editing .evergreen h2,.eg-editing .evergreen .eg-section-title,.eg-editing .eg-schedule li{opacity:1;transform:none;overflow:visible}.eg-editing .eg-photo{clip-path:none}.eg-editing .eg-vine-line{stroke-dashoffset:0}.eg-editing .eg-vine-leaves path,.eg-editing .eg-palette i{opacity:1;transform:none}.eg-editing .eg-progress,.eg-editing .eg-scroll-cue,.eg-editing .eg-journey-rings{display:none}
[data-inline-edit],[data-image-edit]{cursor:pointer;outline:1px dashed transparent;outline-offset:6px;transition:outline-color .18s,background .18s}[data-inline-edit]:hover,[data-inline-edit]:focus{outline-color:#d7b779;background:#fff3}[data-inline-edit][contenteditable=true]{outline:2px solid #d7b779;background:#fff4;cursor:text}[data-image-edit]:hover{outline:3px solid #d7b779;outline-offset:-3px}
.eg-edit-badge{position:absolute;z-index:20;right:.75rem;top:.75rem;display:flex;gap:.35rem;opacity:0;transform:translateY(-4px);transition:.18s}[data-evergreen-block]:hover>.eg-edit-badge{opacity:1;transform:none}.eg-edit-badge button{border:1px solid #ffffff40;background:#111812e8;color:#fff;padding:.45rem .6rem;border-radius:.35rem;font:600 .65rem var(--sans);cursor:pointer;box-shadow:0 4px 16px #0004}.eg-edit-tip{position:fixed;z-index:50;left:50%;bottom:1rem;transform:translateX(-50%);padding:.65rem 1rem;border-radius:999px;background:#111812ed;color:#fff;font:600 .68rem var(--sans);letter-spacing:.04em;box-shadow:0 8px 30px #0006;pointer-events:none}
`;
