export const PRISM_SCRIPT = `(function(){
var d=document,r=d.documentElement,root=d.querySelector('.prism');if(!root)return;r.classList.add('prism-motion');
var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;var sections=[].slice.call(root.querySelectorAll('[data-prism-block],.prism>section:not([data-prism-block])'));
if('IntersectionObserver'in window){var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting)entry.target.classList.add('prism-in')})},{threshold:.1});sections.forEach(function(section){io.observe(section)})}else{sections.forEach(function(section){section.classList.add('prism-in')})}
var progress=root.querySelector('.prism-progress i'),photos=[].slice.call(root.querySelectorAll('[data-prism-parallax]')),stack=[].slice.call(root.querySelectorAll('[data-prism-stack]')),cards=[].slice.call(root.querySelectorAll('[data-prism-card]')),title=root.querySelector('.prism-names'),sculpture=root.querySelector('.prism-sculpture'),cursor=root.querySelector('.prism-cursor'),ticking=false;
cards.forEach(function(card){card.addEventListener('pointerenter',function(){cards.forEach(function(item){item.classList.remove('prism-photo-active')});card.classList.add('prism-photo-active')});card.addEventListener('pointerleave',function(){card.classList.remove('prism-photo-active')})});
function tilt(el,amount){el.addEventListener('pointermove',function(e){if(reduced)return;var b=el.getBoundingClientRect(),x=(e.clientX-b.left)/b.width-.5,y=(e.clientY-b.top)/b.height-.5;el.style.transform='perspective(1000px) rotateX('+(-y*amount)+'deg) rotateY('+(x*amount)+'deg) translateZ(10px)'});el.addEventListener('pointerleave',function(){el.style.transform=''})}if(sculpture)tilt(sculpture,8);var venue=root.querySelector('.prism-venue-glass');if(venue)tilt(venue,4);
if(title&&!reduced){title.addEventListener('pointermove',function(e){var b=title.getBoundingClientRect(),p=Math.max(0,1-Math.abs(e.clientX-(b.left+b.width/2))/(b.width*.7));title.style.letterSpacing=(-.075+p*.035)+'em';title.style.textShadow='0 8px 40px #0007,0 0 '+(p*32)+'px #bcebe0'});title.addEventListener('pointerleave',function(){title.style.letterSpacing='';title.style.textShadow=''})}
var lastX=-100,lastY=-100,angle=0;if(cursor&&!reduced&&matchMedia('(hover:hover)').matches){addEventListener('pointermove',function(e){angle+=3;lastX+=(e.clientX-lastX)*.34;lastY+=(e.clientY-lastY)*.34;cursor.style.left=lastX+'px';cursor.style.top=lastY+'px';cursor.style.setProperty('--cursor-r',angle+'deg');cursor.style.opacity='1'},{passive:true});addEventListener('pointerleave',function(){cursor.style.opacity='0'})}
function paint(){var max=Math.max(1,d.documentElement.scrollHeight-innerHeight),y=scrollY||d.documentElement.scrollTop,p=Math.max(0,Math.min(1,y/max));if(progress)progress.style.transform='scaleX('+p+')';photos.forEach(function(photo){var b=photo.parentElement.getBoundingClientRect(),shift=Math.max(-22,Math.min(22,(innerHeight/2-(b.top+b.height/2))*.038));photo.style.setProperty('--prism-parallax',shift+'px')});stack.forEach(function(card,index){var b=card.getBoundingClientRect(),pin=Math.max(0,Math.min(1,(32-b.top)/180));card.style.setProperty('--prism-stack-scale',(1-pin*(.045+index*.004)).toFixed(3));card.style.setProperty('--prism-stack-y',(pin*index*3)+'px')});ticking=false}
function onScroll(){if(!ticking){requestAnimationFrame(paint);ticking=true}}addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);paint();
})()`.replace(/\n/g, "");

