export const CONSTELLATION_SCRIPT = `(function(){
document.documentElement.classList.add('constellation-motion');var root=document.querySelector('.constellation');if(!root)return;
var sections=[].slice.call(root.querySelectorAll('[data-constellation-block],.constellation>section:not([data-constellation-block])'));
if('IntersectionObserver'in window){var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting)entry.target.classList.add('constellation-in')})},{threshold:.12});sections.forEach(function(section){io.observe(section)})}else{sections.forEach(function(section){section.classList.add('constellation-in')})}
var progress=document.querySelector('.constellation-progress i');var comet=document.querySelector('.constellation-comet');var photos=[].slice.call(root.querySelectorAll('[data-constellation-parallax]'));var timeline=root.querySelector('.constellation-timeline');var ticking=false;
var sculpture=root.querySelector('.constellation-sculpture');if(sculpture&&!matchMedia('(prefers-reduced-motion:reduce)').matches){sculpture.addEventListener('pointermove',function(e){var b=sculpture.getBoundingClientRect(),x=(e.clientX-b.left)/b.width-.5,y=(e.clientY-b.top)/b.height-.5;sculpture.style.transform='perspective(900px) rotateX('+(-y*7)+'deg) rotateY('+(x*9)+'deg)'});sculpture.addEventListener('pointerleave',function(){sculpture.style.transform=''})}
function paint(){var max=Math.max(1,document.documentElement.scrollHeight-innerHeight);var y=scrollY||document.documentElement.scrollTop;var p=Math.max(0,Math.min(1,y/max));if(progress)progress.style.transform='scaleX('+p+')';if(comet){var wave=Math.sin(p*Math.PI*7)*34;comet.style.setProperty('--comet-x',wave+'px');comet.style.setProperty('--comet-y',(p*(innerHeight*.76))+'px');comet.style.setProperty('--comet-rotate',(p*980)+'deg')}photos.forEach(function(photo){var r=photo.parentElement.getBoundingClientRect();var shift=Math.max(-20,Math.min(20,(innerHeight/2-(r.top+r.height/2))*.04));photo.style.setProperty('--constellation-parallax',shift+'px')});if(timeline){var r=timeline.getBoundingClientRect();var tp=Math.max(0,Math.min(1,(innerHeight*.75-r.top)/Math.max(1,r.height*.7)));timeline.style.setProperty('--timeline-progress',tp)}ticking=false}
function onScroll(){if(!ticking){requestAnimationFrame(paint);ticking=true}}addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);paint();
})()`;
