export const SERDCE_FONTS_LINK = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600&family=Montserrat:wght@300;400;500;600&display=swap" rel="stylesheet">';

export const SERDCE_CSS = `
.sheet.serdce{--sc-green:var(--accent,#2e3d2d);--sc-cream:var(--bg,#f5f2e9);--sc-serif:"Cormorant Garamond",Georgia,serif;--sc-sans:"Montserrat","Segoe UI",sans-serif;max-width:none;margin:0;padding:0;overflow:hidden;background:var(--sc-cream) url('/media/invite-serdce/paper.svg') repeat;color:var(--fg,#2e3d2d);box-shadow:none;font:300 17px/1.55 var(--sc-sans)}
body:has(.sheet.serdce){margin:0;background:var(--bg,#f5f2e9)}
body:has(.sheet.serdce) .bits-ambient,body:has(.sheet.serdce) .bits-spotlight{display:none!important}
.sc-section{position:relative;box-sizing:border-box;padding:100px 24px;text-align:center;overflow:hidden;background:transparent}.sc-section *{box-sizing:border-box}
.sc-section h1,.sc-section h2,.sc-section h3{font-family:var(--sc-serif);font-weight:500;line-height:1.05;letter-spacing:0;text-transform:uppercase}
.sc-section h2{margin:0 auto 32px;font-size:clamp(48px,5vw,70px)}.sc-section h2:after{display:none}
.sc-section p{margin:0;font:300 17px/1.7 var(--sc-sans)}
.sc-green{background:var(--sc-green);color:var(--sc-cream)}.sc-green p,.sc-green h2,.sc-green h3{color:inherit}
.sc-cover{height:100svh;min-height:640px;padding:0;background:#737b69;color:#fff}
.sc-cover>img,.sc-cover>.ie-image-placeholder{display:block;width:100%;height:100%;object-fit:cover;object-position:center 47%}
.sc-cover-shade{position:absolute;inset:0;background:linear-gradient(180deg,#14201820 5%,#14201836 45%,#1420187b 100%)}
.sc-cover-copy{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;padding:10vh 20px 12vh}
.sc-cover h1{max-width:850px;margin:0;color:#fff;font-size:clamp(56px,6vw,100px);letter-spacing:.025em}.sc-cover-copy p{margin:10px 0 0;color:#fff;font:500 clamp(20px,2.3vw,34px)/1.1 var(--sc-serif);text-transform:uppercase}
.sc-cover-copy a{margin:auto 0 0;padding:15px 31px;border:1px solid #fff;color:#fff;text-decoration:none;font:400 15px var(--sc-sans);letter-spacing:.07em;text-transform:uppercase}.sc-cover-copy a:hover{background:#fff;color:var(--sc-green)}
.sc-story{padding:0 0 110px}.sc-story-heading{padding:75px 20px 0}.sc-story-heading h2{margin-bottom:4px;font-size:clamp(48px,5vw,76px)}.sc-story-heading p{font:500 25px var(--sc-serif);text-transform:uppercase}
.sc-music-toggle{position:sticky;top:25px;z-index:12;float:left;display:grid;place-items:center;width:66px;height:66px;margin:26px 0 -92px max(4vw,20px);border:0;border-radius:50%;background:var(--sc-green);color:var(--sc-cream);cursor:pointer;font:30px var(--sc-serif)}.sc-music-toggle[aria-pressed=true]{box-shadow:0 0 0 6px #2e3d2d22}
.sc-story-track{max-width:1000px;margin:72px auto 0;padding:0 25px}.sc-story-episode{position:relative;max-width:850px;margin:0 auto 125px;text-align:center}.sc-story-episode:last-child{margin-bottom:95px}
.sc-story-photos{display:flex;align-items:center;justify-content:center;min-height:390px;margin:0 auto 34px}.sc-photo-owner{position:absolute;top:0;left:0;z-index:5}.sc-polaroid{position:relative;flex:0 0 min(350px,75vw);width:min(350px,75vw);height:min(365px,78vw);margin:0;padding:14px 14px 27px;background:#fff;box-shadow:0 12px 25px #3f3a2a25}.sc-polaroid img,.sc-polaroid .ie-image-placeholder{display:block;width:100%;height:100%;object-fit:cover}.sc-rotate-0{transform:rotate(-7deg)}.sc-rotate-1{transform:rotate(6deg)}.sc-rotate-2{transform:rotate(-4deg)}.sc-rotate-3{transform:rotate(5deg)}.sc-story-photos.paired .sc-polaroid:first-of-type{z-index:1;margin-right:-23px;transform:rotate(-9deg) translateY(10px)}.sc-story-photos.paired .sc-polaroid:last-of-type{transform:rotate(9deg) translateY(22px)}
.sc-story-copy{max-width:570px;margin:0 auto}.sc-story-copy h3{margin:0 0 22px;font-size:clamp(30px,3vw,40px)}.sc-story-copy p{white-space:pre-line;font-size:17px;line-height:1.75}.sc-story-quote{max-width:750px;margin:0 auto 0!important;padding:0 20px;font:500 38px/1.12 var(--sc-serif)!important;text-transform:uppercase}.sc-story-arch{position:relative;width:min(1000px,110vw);height:250px;margin:48px auto -58px;border:2px solid var(--sc-green);border-bottom:0;border-radius:50% 50% 0 0 / 100% 100% 0 0}.sc-story-arch:after{content:"";position:absolute;inset:42px 42px -5px;border:1px solid var(--sc-green);border-bottom:0;border-radius:50% 50% 0 0 / 100% 100% 0 0;opacity:.45}.sc-story-arch span{position:absolute;top:-36px;left:50%;transform:translateX(-50%);font:58px var(--sc-serif)}
.sc-story-invite{position:relative;max-width:750px;margin:0 auto;padding:60px 30px 0}.sc-story-invite h2{font-size:54px}.sc-story-invite p{margin:0 auto 30px;max-width:600px}.sc-story-invite strong,.sc-story-invite small{display:block;font:500 30px var(--sc-serif);text-transform:uppercase}.sc-story-invite small{margin-top:24px;font-size:24px;text-transform:none}
.sc-program{padding:120px 24px 105px}.sc-program:before,.sc-rsvp:before{content:"";position:absolute;top:0;left:0;right:0;height:28px;background:radial-gradient(80px 28px at 50% 0,var(--sc-cream) 99%,transparent 100%) 0 0/160px 28px repeat-x}
.sc-program-list{max-width:580px;margin:65px auto 0;text-align:left}.sc-program-list article{margin:0 0 48px}.sc-program-list h3{margin:0 0 8px;font-size:31px}.sc-program-list h3:before{content:"— ";color:#b1bcac}.sc-program-list p{padding-left:31px;font-size:16px}
.sc-venue{padding:118px 24px 75px}.sc-venue h2{margin-bottom:35px}.sc-venue-note{max-width:480px;margin:auto!important}.sc-venue h3{margin:34px auto 7px;font-size:38px}.sc-venue>p{color:#536054}.sc-venue>img,.sc-venue>.ie-image-placeholder{display:block;width:min(650px,100%);aspect-ratio:1.55;object-fit:cover;margin:52px auto 25px}.sc-map-button,.sc-map-section a{display:inline-block;margin-top:20px;padding:13px 26px;border:1px solid var(--sc-green);color:var(--sc-green);text-decoration:none;font:500 14px var(--sc-sans);text-transform:uppercase}
.sc-map-section{padding:30px 24px 110px}.sc-map-section h2{font-size:42px}.sc-map-section p{max-width:450px;margin:auto!important}
.sc-detail{padding:16px 24px 32px}.sc-detail:first-of-type{padding-top:100px}.sc-detail h2{margin-bottom:50px}.sc-detail-body{max-width:580px;margin:0 auto;text-align:left}.sc-detail h3{margin:0 0 12px;font-size:30px}.sc-detail p{font-size:16px}.sc-detail:nth-last-of-type(5){padding-bottom:100px}.sc-detail-quote{max-width:720px;margin:90px auto 50px!important;font:500 39px/1.1 var(--sc-serif)!important;text-transform:uppercase}
.sc-dress{padding:120px 24px}.sc-dress>p{max-width:620px;margin:0 auto!important}.sc-swatches{display:flex;justify-content:center;gap:13px;margin:55px auto 70px}.sc-swatches span{width:80px;height:80px}.sc-dress h3{max-width:760px;margin:55px auto 24px;text-align:left;font-size:30px}.sc-dress-image{display:block;width:min(1140px,100%);height:auto;margin:0 auto}
.sc-dress{padding-bottom:35px}.sc-dress-men{padding:15px 24px 120px}.sc-dress-men h3{max-width:760px;margin:0 auto 26px;text-align:left;font-size:30px}.sc-dress-men img,.sc-dress-men .ie-image-placeholder{display:block;width:min(1140px,100%);height:auto;margin:0 auto}
.sc-rsvp{padding:120px 24px 110px}.sc-rsvp h2{margin-bottom:33px}.sc-rsvp-intro{max-width:520px;margin:0 auto 62px!important}.sc-form{max-width:570px;margin:0 auto;padding:0;text-align:left;font-family:var(--sc-sans)}.sc-form fieldset{margin:0 0 35px;padding:0;border:0}.sc-form legend,.sc-field>span{display:block;margin:0 0 8px;font:500 19px var(--sc-sans);color:#f5f2e9}.sc-form label{display:block;color:#e6e9e2;font:300 16px/1.55 var(--sc-sans)}.sc-form input[type=radio],.sc-form input[type=checkbox]{width:18px;height:18px;margin:0 7px 0 0;vertical-align:-3px;accent-color:#dfe6d7}.sc-field{margin-bottom:32px}.sc-field small,.sc-form fieldset small{display:block;margin-bottom:12px;color:#c4cdbf;font:300 13px var(--sc-sans)}.sc-field input{display:block;width:100%;padding:12px 0;border:0;border-bottom:1px solid #c5cec0;border-radius:0;background:transparent;color:#fff;font:300 16px var(--sc-sans)}.sc-field input::placeholder{color:#aab6a6}.sc-form button{display:block;margin:40px auto 0;padding:15px 60px;border:1px solid #f5f2e9;background:transparent;color:#f5f2e9;cursor:pointer;font:500 15px var(--sc-sans);letter-spacing:.08em;text-transform:uppercase}.sc-form button:hover{background:#f5f2e9;color:var(--sc-green)}
.sc-form-ok,.sc-form-error{max-width:550px;margin:0 auto 25px!important}.sc-form-error{color:#ffd0c5!important}
.sc-countdown{padding:115px 24px 95px}.sc-countdown h2{font-size:40px}.sc-clock{display:flex;justify-content:center;max-width:610px;margin:40px auto 95px}.sc-clock>div{flex:1;border-right:1px solid #879383}.sc-clock>div:last-child{border:0}.sc-clock strong{display:block;font:500 70px/1 var(--sc-serif);font-variant-numeric:tabular-nums}.sc-clock span{font:400 14px var(--sc-sans)}.sc-quote{font:500 41px/1.1 var(--sc-serif)!important;text-transform:uppercase}
.sc-contact{padding:75px 24px}.sc-contact p{max-width:490px;margin:0 auto!important;white-space:pre-line}.sc-contact a{display:inline-block;margin-top:20px;color:var(--sc-green);font:500 20px var(--sc-serif);text-decoration:none}.sc-farewell{padding:80px 24px 110px}.sc-farewell h2{margin-bottom:15px}.sc-farewell p{font:500 25px var(--sc-serif)}
.serdce .foot{margin:0;padding:26px 24px 45px;background:var(--sc-cream);color:#657064;font:300 13px var(--sc-sans)}.serdce .who{position:absolute;top:10px;right:10px;z-index:5;padding:5px 8px;background:#f5f2e9e6;color:#657064;font:400 11px var(--sc-sans)}
@media(max-width:650px){.sc-section h2{font-size:46px}.sc-cover{min-height:600px}.sc-cover>img{object-position:53% center}.sc-cover-copy{padding-top:16vh}.sc-cover h1{font-size:58px}.sc-cover-copy p{font-size:22px}.sc-story-heading{padding-top:65px}.sc-story-track{margin-top:45px;padding:0 18px}.sc-story-episode{margin-bottom:96px}.sc-story-photos{min-height:280px;margin-bottom:25px}.sc-polaroid{flex-basis:68vw;width:68vw;height:71vw;max-height:340px}.sc-story-photos.paired .sc-polaroid{flex-basis:49vw;width:49vw;height:53vw;padding:8px 8px 17px}.sc-story-copy h3{font-size:29px}.sc-story-copy p{font-size:15px}.sc-story-quote{font-size:31px!important}.sc-story-arch{height:150px;margin-top:58px}.sc-story-arch:after{inset:24px 24px -4px}.sc-story-invite{padding-top:50px}.sc-story-invite h2{font-size:43px}.sc-story-invite p{font-size:15px}.sc-music-toggle{width:52px;height:52px;top:18px;font-size:25px}.sc-program,.sc-venue,.sc-dress,.sc-rsvp,.sc-countdown{padding-top:95px;padding-bottom:80px}.sc-program-list{margin-top:50px}.sc-program-list h3{font-size:28px}.sc-venue h3{font-size:32px}.sc-swatches{gap:6px;margin:38px auto}.sc-swatches span{width:54px;height:54px}.sc-dress h3{font-size:25px;margin-top:35px}.sc-clock{margin-bottom:65px}.sc-clock strong{font-size:44px}.sc-clock span{font-size:11px}.sc-quote{font-size:33px!important}.sc-detail{padding-left:28px;padding-right:28px}.sc-detail h3{font-size:27px}}
`.replace(/\n/g, "");
