export const SILK_CSS = `
body{background:#dfc5bf;background-image:radial-gradient(circle at 18% 9%,#fff8 0 1px,transparent 2px),linear-gradient(125deg,#ead6d0,#d8b9b2 46%,#efdeda);background-size:18px 18px,auto}
.sheet.silk{position:relative;max-width:40rem;background:#fff8f2;overflow:hidden;box-shadow:0 28px 90px #6a36353d}
.silk>section{position:relative;margin:0;overflow:hidden}.silk [data-silk-block]{padding:5.4rem 2.25rem}.silk [data-silk-block]>*:not(.silk-flower):not(.ie-tools){position:relative;z-index:2}
.silk h2{margin:0 auto 1.15rem;max-width:14ch;color:#713b38;font:italic 400 clamp(2.4rem,9vw,3.6rem)/1.02 var(--serif);letter-spacing:-.035em;text-align:center;text-transform:none}.silk h2::after{display:none}.silk-copy{max-width:29rem;margin:0 auto;color:#806b66;font:1.02rem/1.9 var(--serif);white-space:pre-line;text-align:center}.silk-section-tag{margin:0 0 .85rem;color:#a84f49;font:600 .6rem/1.4 var(--sans);letter-spacing:.28em;text-transform:uppercase;text-align:center}.silk-rule{display:block;width:2.8rem;height:1px;margin:1.3rem auto;background:#a84f49}.silk-progress{position:fixed!important;z-index:90!important;left:0;right:0;top:0;height:3px;background:#ffffff44;pointer-events:none}.silk-progress i{display:block;width:100%;height:100%;background:linear-gradient(90deg,#743231,#ce7c70,#f0c8be);transform:scaleX(0);transform-origin:left;box-shadow:0 0 14px #a84f4988}
.silk-cover{min-height:100svh!important;padding:0!important;background:#5b302f;color:#fff}.silk-cover-photo{position:absolute!important;z-index:0!important;inset:0}.silk-cover-photo img{width:100%;height:100%;object-fit:cover;object-position:center;display:block;transform:scale(1.035)}.silk-cover-photo::after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,#50201d22,#50201d0a 45%,#421a1955)}.silk-cover-wave{position:absolute!important;z-index:2!important;right:-9%;bottom:-8%;width:80%;height:91%;display:flex;align-items:flex-end;background:#fff8f2;color:#5b302f;border-radius:62% 0 0 43%;box-shadow:-15px -4px 40px #4a19192c}.silk-cover-wave::before{content:'';position:absolute;inset:1rem 0 0 1rem;border:1px solid #dba9a0;border-right:0;border-bottom:0;border-radius:62% 0 0 43%;opacity:.55}.silk-cover-copy{width:100%;padding:7rem 2.1rem 5.5rem 3.5rem;text-align:center}.silk-kicker{margin:0 auto;color:#a84f49;font:600 .58rem/1.7 var(--sans);letter-spacing:.28em;text-transform:uppercase;max-width:18rem}.silk-names{margin:1.1rem 0 1rem;color:#8d3e3a;font:italic 400 clamp(3.3rem,12vw,5.25rem)/.86 var(--serif);letter-spacing:-.055em}.silk-names span{display:block}.silk-names i{display:block;margin:.12em 0;color:#ba655e;font-size:.7em;font-weight:400}.silk-date{margin:0;color:#713b38;font:.7rem/1.7 var(--sans);letter-spacing:.17em;text-transform:uppercase}.silk-cover-note{max-width:19rem;margin:1.3rem auto 0;color:#8d6f69;font:italic 1.05rem/1.5 var(--serif);white-space:pre-line}.silk-scroll{position:absolute!important;z-index:4!important;left:1.5rem;bottom:2rem;display:flex;align-items:center;gap:.7rem;color:#fff}.silk-scroll span{display:block;width:2.5rem;height:1px;background:#fff;animation:silk-pulse 2s ease-in-out infinite}.silk-scroll small{font:500 .52rem var(--sans);letter-spacing:.2em;text-transform:uppercase}.silk-petals{position:absolute!important;z-index:3!important;inset:0;pointer-events:none}.silk-petals i{position:absolute;width:14px;height:23px;border-radius:80% 10% 70% 20%;background:linear-gradient(135deg,#f3c5bd,#a84f49);opacity:0;animation:silk-petal 9s linear infinite}.silk-petals i:nth-child(1){left:8%;animation-delay:-2s}.silk-petals i:nth-child(2){left:19%;animation-delay:-6s}.silk-petals i:nth-child(3){left:31%;animation-delay:-4s}.silk-petals i:nth-child(4){left:45%;animation-delay:-8s}.silk-petals i:nth-child(5){left:57%;animation-delay:-1s}.silk-petals i:nth-child(6){left:70%;animation-delay:-5s}.silk-petals i:nth-child(7){left:81%;animation-delay:-3s}.silk-petals i:nth-child(8){left:91%;animation-delay:-7s}.silk-petals i:nth-child(9){left:64%;animation-delay:-9s}
.silk-story{min-height:39rem;background:linear-gradient(155deg,#fff8f2 0 56%,#f3ddd7 56%);text-align:center}.silk-note-card{width:12.5rem;margin:3rem auto 0;padding:2.3rem 1.2rem 1.3rem;background:#e9bbb2;color:#783c39;box-shadow:0 16px 40px #7c373727;transform:rotate(-3deg);font:italic 1.35rem/1.25 var(--serif)}.silk-note-card::before{content:'';position:absolute;inset:.55rem;border:1px solid #fff8}.silk-note-card i{display:block;margin-top:.75rem;font-style:normal}
.silk-flower{position:absolute!important;z-index:1!important;width:10.5rem;color:#b45d55;opacity:.34;pointer-events:none}.silk-flower path,.silk-flower circle{vector-effect:non-scaling-stroke}.silk-stem{stroke:currentColor;stroke-width:1.1;stroke-dasharray:1;stroke-dashoffset:1}.silk-leaves path{fill:#c68278;opacity:.55}.silk-blossom path{fill:#d68a80;stroke:#9c4945;stroke-width:.8}.silk-blossom circle{fill:#8f3e3a}.silk-flower-left{left:-2rem;bottom:-1rem}.silk-flower-right{right:-1.5rem;top:.8rem;transform:scaleX(-1)}.silk-in .silk-stem{animation:silk-draw 1.8s .2s ease-out forwards}
.silk-weekend{background:#f6e4de}.silk-weekend-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-top:2.5rem}.silk-event-card{position:relative;margin:0;padding:.65rem .65rem 1rem;background:#fffaf5;border:1px solid #ecd3cd;border-radius:1rem;box-shadow:0 13px 30px #7a3d3420;transform:translateY(18px) rotate(var(--silk-tilt,0deg));opacity:0;transition:transform .8s cubic-bezier(.2,.7,.2,1),opacity .8s}.silk-event-card:nth-child(2){--silk-tilt:1.5deg}.silk-event-card:nth-child(3){--silk-tilt:-1.4deg}.silk-event-card:nth-child(4){--silk-tilt:1deg}.silk-event-main{grid-column:1/-1;display:grid;grid-template-columns:1.15fr .85fr;align-items:center;padding-bottom:.65rem}.silk-in .silk-event-card{opacity:1;transform:translateY(0) rotate(var(--silk-tilt,0deg))}.silk-in .silk-event-card:nth-child(2){transition-delay:.1s}.silk-in .silk-event-card:nth-child(3){transition-delay:.2s}.silk-in .silk-event-card:nth-child(4){transition-delay:.3s}.silk-event-photo{height:12rem;overflow:hidden;border-radius:.65rem}.silk-event-main .silk-event-photo{height:15rem}.silk-event-photo img{width:100%;height:112%;object-fit:cover;display:block;transform:translate3d(0,var(--silk-parallax,0px),0) scale(1.04)}.silk-event-card figcaption{padding:.85rem .2rem 0;color:#5b302f;font:italic 1.02rem/1.25 var(--serif);text-align:center}.silk-event-main figcaption{padding:1rem;font-size:1.2rem}.silk-event-card b{position:absolute;right:1rem;top:1rem;display:grid;place-items:center;width:1.8rem;height:1.8rem;border-radius:50%;background:#8f3f3c;color:#fff;font:500 .58rem var(--sans);letter-spacing:.08em}.silk-empty{display:block;width:100%;height:100%;background:#efd8d1}
.silk>section:not([data-silk-block]){padding:4.7rem 2rem;background:#fff8f2;text-align:center}.silk>section:not([data-silk-block]) h2{color:#713b38}.silk .countdown{gap:.65rem}.silk .countdown div{min-width:4.2rem;padding:1rem .4rem;border:1px solid #e7c9c2;border-radius:1rem;background:#fff}.silk .countdown b{color:#8f3f3c}.silk .countdown span{color:#9b716a;font-size:.6rem}
.silk-venue{padding-left:1.1rem!important;padding-right:1.1rem!important;background:#fff8f2}.silk-venue-photo{height:29rem;overflow:hidden;border-radius:48% 48% 1.25rem 1.25rem;box-shadow:0 18px 48px #6c302c28}.silk-venue-photo img{width:100%;height:112%;object-fit:cover;display:block;transform:translate3d(0,var(--silk-parallax,0px),0) scale(1.04)}.silk-venue-photo::after{content:'';position:absolute;inset:0;background:linear-gradient(transparent 55%,#4e201f99)}.silk-venue-photo span{position:absolute;z-index:2;left:0;right:0;bottom:1.5rem;color:#fff;font:600 .62rem var(--sans);letter-spacing:.27em;text-transform:uppercase;text-align:center}.silk-venue-card{width:calc(100% - 3rem);margin:-3.5rem auto 0;padding:2.5rem 1.5rem 2rem;background:#fffaf6;border:1px solid #ecd2ca;border-radius:1.2rem;box-shadow:0 18px 40px #6b302724;text-align:center}.silk-venue-card h2{font-size:2.4rem}.silk-address{margin:-.35rem 0 1.2rem;color:#a84f49;font:.62rem/1.5 var(--sans);letter-spacing:.17em;text-transform:uppercase}
.silk-timeline{background:#6e302f;color:#fcedea}.silk-timeline h2{color:#fff}.silk-timeline .silk-section-tag{color:#eebbb1}.silk-timeline ol{list-style:none;margin:2.6rem auto 0;padding:0;max-width:28rem}.silk-timeline li{position:relative;display:grid;grid-template-columns:4.7rem 1fr;gap:1.2rem;align-items:start;padding:1.25rem 2.2rem 1.25rem 0;border-top:1px solid #f4d4cc33;opacity:0;transform:translateX(28px);transition:.65s ease}.silk-in.silk-timeline li{opacity:1;transform:none}.silk-in.silk-timeline li:nth-child(2){transition-delay:.1s}.silk-in.silk-timeline li:nth-child(3){transition-delay:.2s}.silk-in.silk-timeline li:nth-child(4){transition-delay:.3s}.silk-timeline time{color:#efb4aa;font:italic 1.15rem var(--serif);text-align:right}.silk-timeline strong{display:block;color:#fff;font:400 1.18rem var(--serif)}.silk-timeline small{display:block;margin-top:.3rem;color:#e5c8c2;font:.75rem/1.45 var(--sans)}.silk-timeline .silk-flower{color:#f0beb4;opacity:.16}.silk-add-detail{display:block;margin:2rem auto 0;padding:.75rem 1rem;border:1px dashed #efb4aa;border-radius:999px;background:transparent;color:#fff;font:600 .72rem var(--sans);cursor:pointer}
.silk-dress{text-align:center;background:linear-gradient(145deg,#f6e3dd,#fff8f2)}.silk-palette{display:flex;justify-content:center;gap:.65rem;margin-top:2.2rem}.silk-palette i{display:block;width:3rem;height:3rem;border-radius:50%;border:4px solid #fff;box-shadow:0 7px 20px #773c3528;transform:scale(0);transition:transform .55s cubic-bezier(.2,.8,.2,1)}.silk-in .silk-palette i{transform:scale(1)}.silk-in .silk-palette i:nth-child(2){transition-delay:.08s}.silk-in .silk-palette i:nth-child(3){transition-delay:.16s}.silk-in .silk-palette i:nth-child(4){transition-delay:.24s}.silk-in .silk-palette i:nth-child(5){transition-delay:.32s}
.silk-rsvp{text-align:center;background:#fff8f2}.silk-rsvp h2{font-size:clamp(3rem,11vw,4.6rem)}.silk-cta{display:inline-flex;align-items:center;justify-content:center;gap:1rem;min-width:16rem;margin-top:2.2rem;padding:1rem 1.5rem;border-radius:999px;background:linear-gradient(100deg,#8d3e3a,#b65a53);color:#fff;text-decoration:none;font:500 .73rem var(--sans);letter-spacing:.14em;text-transform:uppercase;box-shadow:0 12px 28px #8f3e3a3d;overflow:hidden}.silk-cta::before{content:'';position:absolute;inset:0;background:linear-gradient(105deg,transparent 32%,#fff5 50%,transparent 68%);transform:translateX(-130%);animation:silk-shine 4s 1s ease-in-out infinite}.silk-cta span{font-size:1.15rem}.silk-cta b{position:relative;font:inherit;font-weight:inherit}.silk-answer{margin:2rem 0 0;color:#8f3e3a;font:italic 1.25rem var(--serif)}
.silk-closing{min-height:31rem;text-align:center;background:linear-gradient(#6a2d2edd,#6a2d2eee),url('/media/invite-silk/dinner.webp') center/cover;color:#fff;display:flex;flex-direction:column;justify-content:center}.silk-closing h2{color:#fff}.silk-closing .silk-copy{color:#f2d8d3}.silk-script{margin:0 0 .9rem;color:#efbcb2;font:italic 1.35rem var(--serif)}.silk-closing .silk-flower{color:#f2b9af;opacity:.2}.silk .foot{margin:0;padding:1.5rem 1rem 2rem;background:#572524;color:#dfb7b1;text-align:center;font:.62rem var(--sans);letter-spacing:.12em}
.silk-ribbon{position:fixed!important;z-index:0!important;width:17rem;height:100vh;top:0;pointer-events:none;opacity:.16;filter:blur(.2px);background:linear-gradient(90deg,transparent,#fff9,transparent);transform:rotate(18deg);animation:silk-ribbon 10s ease-in-out infinite}.silk-ribbon-one{left:-9rem}.silk-ribbon-two{right:-10rem;animation-delay:-5s;transform:rotate(-18deg)}
.silk-cover-photo .ie-image-placeholder{height:100%;min-height:42rem;border:0!important;background:#7a3838!important;color:#f7ddd7!important}.silk-venue-photo .ie-image-placeholder,.silk-event-photo .ie-image-placeholder{height:100%;min-height:inherit}
.silk-motion .silk>section{opacity:0;transform:translateY(32px);transition:opacity .95s ease,transform .95s cubic-bezier(.2,.75,.2,1)}.silk-motion .silk>section.silk-cover,.silk-motion .silk>section.silk-in{opacity:1;transform:none}.silk-motion .silk-cover-photo img{transform:translate3d(0,var(--silk-cover-y,0px),0) scale(1.06)}
@keyframes silk-draw{to{stroke-dashoffset:0}}@keyframes silk-pulse{0%,100%{transform:scaleX(.35);opacity:.45}50%{transform:scaleX(1);opacity:1}}@keyframes silk-petal{0%{transform:translate3d(0,-12vh,0) rotate(0);opacity:0}10%{opacity:.7}100%{transform:translate3d(55px,112vh,0) rotate(560deg);opacity:0}}@keyframes silk-shine{0%,55%{transform:translateX(-130%)}82%,100%{transform:translateX(130%)}}@keyframes silk-ribbon{0%,100%{translate:0 -4%;rotate:18deg}50%{translate:2rem 5%;rotate:24deg}}
@media(max-width:430px){.silk [data-silk-block]{padding-left:1.5rem;padding-right:1.5rem}.silk-cover-wave{right:-13%;width:86%}.silk-cover-copy{padding-left:1.4rem;padding-right:calc(13vw + 1.2rem)}.silk-names{font-size:clamp(2.6rem,11vw,3.3rem)}.silk-weekend-grid{gap:.55rem}.silk-event-card{padding:.45rem .45rem .85rem}.silk-event-photo{height:10rem}.silk-event-main .silk-event-photo{height:13rem}.silk-event-main figcaption{padding:.6rem;font-size:1rem}.silk-palette{gap:.35rem}.silk-palette i{width:2.55rem;height:2.55rem}}
@media(max-width:360px){.silk [data-silk-block]{padding-left:1.1rem;padding-right:1.1rem}.silk-cover-wave{right:0;width:94%}.silk-cover-copy{padding-left:2.15rem;padding-right:1.1rem}.silk-kicker,.silk-date{overflow-wrap:anywhere}.silk-names{font-size:clamp(2.1rem,13vw,3.3rem)}.silk-weekend-grid{grid-template-columns:1fr}.silk-event-main{grid-column:auto}.silk-event-photo,.silk-event-main .silk-event-photo{height:14rem}.silk-timeline li{grid-template-columns:3.8rem 1fr;gap:.75rem}}
@media(prefers-reduced-motion:reduce){.silk-motion .silk>section{opacity:1;transform:none;transition:none}.silk-petals,.silk-ribbon{display:none}.silk-stem{stroke-dashoffset:0}.silk-event-card,.silk-timeline li,.silk-palette i{opacity:1;transform:none;transition:none}.silk-cta::before{display:none}}
`.replace(/\n/g, "");

export const SILK_EDITOR_CSS = `
html.ie-editing .silk>section,html.ie-editing .silk-event-card,html.ie-editing .silk-timeline li,html.ie-editing .silk-palette i{opacity:1;transform:none;transition:none}
html.ie-editing .silk-petals,html.ie-editing .silk-progress,html.ie-editing .silk-ribbon,html.ie-editing .silk-scroll{display:none}
html.ie-editing .silk-stem{stroke-dashoffset:0}
`;
