/** Local, dependency-free interactions; source-site scripts are never loaded. */
export const WEDWED_SCRIPT = `(function(){
var d=document,editing=d.documentElement.classList.contains('ie-editing');
function clock(){d.querySelectorAll('[data-wv-until]').forEach(function(section){var total=Math.max(0,Math.floor((Number(section.dataset.wvUntil)-Date.now())/1000));var values={days:Math.floor(total/86400),hours:Math.floor(total/3600)%24,minutes:Math.floor(total/60)%60,seconds:total%60};section.querySelectorAll('[data-clock-unit]').forEach(function(el){var value=String(values[el.dataset.clockUnit]).padStart(2,'0');if(el.dataset.clockDigits==='true'){el.innerHTML=value.split('').map(function(c){return '<div class="sm-timer-time_number"><span class="sm-timer-time_number-span">'+c+'</span></div>'}).join('')}else el.textContent=value})})}clock();setInterval(clock,1000);
d.querySelectorAll('[data-carousel]').forEach(function(slider){
var slides=Array.from(slider.children).filter(function(el){return !el.matches('[data-wv-prev],[data-wv-next],button,.wv-carousel-controls')});if(!slides.length)return;
var current=0,scope=slider.parentElement,prev=scope.querySelector('[data-wv-prev]'),next=scope.querySelector('[data-wv-next]'),counter=scope.querySelector('[data-wv-counter]'),total=scope.querySelector('[data-wv-total]');
slides.forEach(function(el){el.dataset.wvSlide='';el.removeAttribute('aria-hidden')});
if(!prev||!next){var controls=d.createElement('div');controls.className='wv-carousel-controls';controls.innerHTML='<button type="button" data-wv-prev>←</button><span data-wv-counter="total"></span><button type="button" data-wv-next>→</button>';slider.insertAdjacentElement('afterend',controls);prev=controls.querySelector('[data-wv-prev]');next=controls.querySelector('[data-wv-next]');counter=controls.querySelector('span')}
if(counter)counter.setAttribute('aria-live','polite');if(total)total.textContent=String(slides.length);
function show(){slides.forEach(function(el,i){el.classList.toggle('wv-current',i===current);el.setAttribute('aria-hidden',String(i!==current))});if(counter)counter.textContent=(current+1)+(counter.dataset.wvCounter==='total'?'/'+slides.length:'')}
[prev,next].forEach(function(button,i){button.setAttribute('aria-label',d.documentElement.lang==='en'?(i?'Next slide':'Previous slide'):(i?'Следующий слайд':'Предыдущий слайд'));button.setAttribute('role','button');button.setAttribute('tabindex','0');function move(){current=(current+(i?1:-1)+slides.length)%slides.length;show()}button.addEventListener('click',move);if(button.tagName!=='BUTTON')button.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();move()}})});
var start=0;slider.addEventListener('touchstart',function(e){start=e.changedTouches[0].clientX},{passive:true});slider.addEventListener('touchend',function(e){var delta=e.changedTouches[0].clientX-start;if(Math.abs(delta)>40){current=(current+(delta<0?1:-1)+slides.length)%slides.length;show()}},{passive:true});show()});
d.querySelectorAll('a[href="javascript:void(0)"]').forEach(function(a){a.removeAttribute('href')});
d.querySelectorAll('form[data-demo]').forEach(function(form){form.addEventListener('submit',function(e){e.preventDefault();form.querySelector('.wv-demo-note').hidden=false})});
d.addEventListener('click',function(e){var name=e.target.closest('[data-wedding-names]');if(name&&d.documentElement.classList.contains('ie-editing')){e.preventDefault();parent.postMessage({source:'invite-canvas',kind:'wedding-edit',focus:'names'},'*')}});
if(!editing&&'IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion:reduce)').matches){var observer=new IntersectionObserver(function(items){items.forEach(function(item){if(item.isIntersecting){item.target.classList.add('wv-in');observer.unobserve(item.target)}})},{threshold:.06});d.querySelectorAll('main>section').forEach(function(section,i){if(i&&section.getBoundingClientRect().top>innerHeight){section.classList.add('wv-reveal');observer.observe(section)}})}
})()`;
