import { defaultTheme } from "@/lib/invite-theme";
import type { InviteTemplate } from "@/lib/invite-templates";

/** Only standard editor blocks: photographs and every line of copy stay editable. */
export const PROMISE_TEMPLATE: InviteTemplate = {
  id: "promise",
  name: "Обещание",
  mood: "Романтика итальянского сада: пудровые розы, кремовая бумага, большая фотообложка и плавные анимации. Все фотографии и тексты можно заменить.",
  theme: {
    ...defaultTheme(),
    template: "promise",
    bg: "#efe7de",
    card: "#faf6f0",
    ink: "#49372c",
    muted: "#806b5d",
    accent: "#966c5c",
    line: "#e2cec3",
    leaf: "#8a9679",
    headingFont: "didona",
    bodyFont: "antiqua",
    corner: "soft",
    divider: "line",
    cover: "photo",
    timeline: "row",
    sections: "flat",
    dateStyle: "line",
    intro: "none",
    decor: "none",
    paper: true,
    frame: false,
    timelineIcons: true,
    capsHeadings: false,
    align: "center",
  },
  blocks: [
    { type: "COVER", content: { v: 1, title: "Приглашаем вас на нашу свадьбу", names: "Имя и Имя", dateText: "", subtitle: "Один день. Одна любовь. Целая жизнь вместе.", imageUrl: "" } },
    { type: "TEXT", content: { v: 1, title: "Быть рядом — бесценно", text: "Есть моменты, которые хочется разделить с самыми близкими.\nМы будем счастливы, если в день начала нашей семьи вы будете рядом.\n\nПриглашаем вас стать частью нашей истории любви." } },
    { type: "CALENDAR", content: { v: 1, title: "Наш особенный день", message: "Сохраните эту дату. Впереди — самые тёплые воспоминания." } },
    { type: "COUNTDOWN", content: { v: 1, title: "До нашей встречи", doneText: "Этот день настал. До встречи на празднике!" } },
    { type: "PHOTOS", content: { v: 1, title: "Место, где начинается праздник", items: [{ imageUrl: "", caption: "Здесь будет фотография нашей площадки" }] } },
    { type: "VENUE", content: { v: 1, title: "Ждём вас здесь", name: "Название вашей площадки", address: "Город, улица, дом", note: "Церемония под открытым небом, тёплый вечер и самые близкие люди." } },
    { type: "MAP", content: { v: 1, title: "Дорога к нам", yandexUrl: "", googleUrl: "", note: "Точный маршрут и подробности про парковку мы добавим ближе к празднику." } },
    { type: "TIMELINE", content: { v: 1, title: "Маленькие моменты большого дня", items: [
      { time: "16:00", title: "Встреча гостей", note: "Объятия, лёгкие закуски и первые фотографии" },
      { time: "16:30", title: "Церемония", note: "Самые важные слова друг другу" },
      { time: "17:30", title: "Праздничный ужин", note: "Тосты, улыбки и истории о любви" },
      { time: "20:00", title: "Танцы под звёздами", note: "Пусть этот вечер длится чуть дольше" },
    ] } },
    { type: "DRESSCODE", content: { v: 1, title: "В оттенках нежности", text: "Нам будет особенно приятно, если вы поддержите настроение нашего дня.\nМягкие природные оттенки, лёгкие ткани и ваше прекрасное настроение.", palette: ["#eee2d3", "#d9b8ab", "#b98e80", "#9ca389", "#666f55"] } },
    { type: "PHOTOS", content: { v: 1, title: "Наша маленькая вечность", items: [{ imageUrl: "", caption: "С этого всё началось" }, { imageUrl: "", caption: "И столько прекрасного впереди" }] } },
    { type: "TEXT", content: { v: 1, title: "Несколько тёплых пожеланий", text: "Самый важный подарок для нас — ваше присутствие.\nВместо букета можно привезти бутылку любимого вина: мы сохраним её для одного из наших семейных вечеров.\n\nЕсли у вас есть вопросы или сюрприз для нас, свяжитесь с нашим организатором — контакты мы добавим здесь." } },
    { type: "RSVP_FORM", content: { v: 1, title: "Вы разделите с нами этот день?", text: "Пожалуйста, расскажите о своих планах заранее.\nТак мы сможем позаботиться о каждом госте.", buttonLabel: "С радостью ответим" } },
    { type: "TEXT", content: { v: 1, title: "До встречи, с любовью", text: "Спасибо, что вы — часть нашей истории.\nВсё самое прекрасное только начинается." } },
  ],
};
